// Code generated by Fern. DO NOT EDIT.

package accounts

import (
	context "context"

	coreapigo "github.com/namedotcom/core-api-go"
	core "github.com/namedotcom/core-api-go/core"
	internal "github.com/namedotcom/core-api-go/internal"
	option "github.com/namedotcom/core-api-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Creates a new sub-account under your authenticated reseller account and returns API credentials for the new account.  This endpoint is only available to approved reseller accounts. Contact name.com support to request access.
func (c *Client) CreateAccount(
	ctx context.Context,
	request *coreapigo.CreateAccountRequest,
	opts ...option.RequestOption,
) (*coreapigo.CreateAccountResponse, error) {
	response, err := c.WithRawResponse.CreateAccount(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
