// Code generated by Fern. DO NOT EDIT.

package orders

import (
	context "context"

	coreapigo "github.com/namedotcom/core-api-go"
	core "github.com/namedotcom/core-api-go/core"
	internal "github.com/namedotcom/core-api-go/internal"
	option "github.com/namedotcom/core-api-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Retrieves a list of all orders placed in the account.
//
// Example:
//
//	request := &coreapigo.ListOrdersRequest{}
//	client.Orders.ListOrders(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) ListOrders(
	ctx context.Context,
	request *coreapigo.ListOrdersRequest,
	opts ...option.RequestOption,
) (*coreapigo.ListOrdersResponse, error) {
	response, err := c.WithRawResponse.ListOrders(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Fetches full details about a specific order using its ID. This includes domains, prices, and timestamps.  Useful for confirming transactions, receipts, or generating invoices.
//
// Example:
//
//	request := &coreapigo.GetOrderRequest{
//	    OrderID: 1,
//	}
//	client.Orders.GetOrder(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) GetOrder(
	ctx context.Context,
	request *coreapigo.GetOrderRequest,
	opts ...option.RequestOption,
) (*coreapigo.Order, error) {
	response, err := c.WithRawResponse.GetOrder(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
