// Code generated by Fern. DO NOT EDIT.

package tldpricing

import (
	context "context"

	coreapigo "github.com/namedotcom/core-api-go"
	core "github.com/namedotcom/core-api-go/core"
	internal "github.com/namedotcom/core-api-go/internal"
	option "github.com/namedotcom/core-api-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// This endpoint returns an alphabetical list of all TLDs supported by name.com, including pricing for each supported order type. All prices are in US Dollars (USD) and apply to non-premium domains. name.com provides three pricing types for each TLD:
// - Account-Level Pricing - Your price, including any applicable rebates, promotions, or account-level discounts. This is referenced as 'registrationprice', 'renewalprice', 'transferinprice' and 'domainrestorationprice' in this endpoint.
// - Original Pricing (No Discounts Applied) - The suggested retail price (MSRP) before any discounts are applied.
// - Retail Pricing (Public Site Pricing) - The current public retail price on name.com, including any public rebates or promotions, but before any account-level discounts.
//
// **Important Notes:**
// - Promo codes are not supported through the API, and therefore are not reflected in any pricing values returned.
// - General TLD pricing only: This represents standard pricing for domains registered under the specified TLD. Pricing for specific domains may differ based on multiple factors (e.g., premium classifications, registry pricing rules). To retrieve pricing for an individual domain, use the GetPricingForDomain endpoint.
// - Availability: If a pricing value is returned as null, that product type is not currently supported for the TLD. (Example: registrationPrice = null means registrations are not currently available.)
// - If you do not have account level pricing, the retail price will always match your account level price. (e.g., registration price = registration retail price)
//
// Example:
//
//	request := &coreapigo.TldPriceListRequest{
//	    Duration: coreapigo.Int(
//	        1,
//	    ),
//	}
//	client.TldPricing.TldPriceList(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) TldPriceList(
	ctx context.Context,
	request *coreapigo.TldPriceListRequest,
	opts ...option.RequestOption,
) (*coreapigo.TldPriceListResponse, error) {
	response, err := c.WithRawResponse.TldPriceList(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
