// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/namedotcom/core-api-go/internal"
	big "math/big"
	time "time"
)

var (
	createAccountRequestFieldAccount = big.NewInt(1 << 0)
	createAccountRequestFieldAPITos  = big.NewInt(1 << 1)
	createAccountRequestFieldTos     = big.NewInt(1 << 2)
)

type CreateAccountRequest struct {
	// The account details for the new account being created.
	Account *AccountRequest `json:"account" url:"-"`
	// Must be set to true to indicate acceptance of the API Terms of Service.
	APITos bool `json:"apiTos" url:"-"`
	// Must be set to true to indicate acceptance of the general Terms of Service.
	Tos bool `json:"tos" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CreateAccountRequest) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetAccount sets the Account field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateAccountRequest) SetAccount(account *AccountRequest) {
	c.Account = account
	c.require(createAccountRequestFieldAccount)
}

// SetAPITos sets the APITos field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateAccountRequest) SetAPITos(apiTos bool) {
	c.APITos = apiTos
	c.require(createAccountRequestFieldAPITos)
}

// SetTos sets the Tos field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateAccountRequest) SetTos(tos bool) {
	c.Tos = tos
	c.require(createAccountRequestFieldTos)
}

func (c *CreateAccountRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateAccountRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*c = CreateAccountRequest(body)
	return nil
}

func (c *CreateAccountRequest) MarshalJSON() ([]byte, error) {
	type embed CreateAccountRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

// Account lists all the data for an account. This schema is used for requests.
var (
	accountRequestFieldContacts    = big.NewInt(1 << 0)
	accountRequestFieldAccountID   = big.NewInt(1 << 1)
	accountRequestFieldAccountName = big.NewInt(1 << 2)
	accountRequestFieldAutoRenew   = big.NewInt(1 << 3)
	accountRequestFieldCreateDate  = big.NewInt(1 << 4)
	accountRequestFieldPassword    = big.NewInt(1 << 5)
)

type AccountRequest struct {
	// Contact information associated with this account.
	Contacts *ContactsRequest `json:"contacts,omitempty" url:"contacts,omitempty"`
	// AccountId is the unique id of account.
	AccountID *int `json:"accountId,omitempty" url:"accountId,omitempty"`
	// AccountName is the unique name of the account.  Minimum length is 6 characters, maximum length is 60.
	AccountName *string `json:"accountName,omitempty" url:"accountName,omitempty"`
	// When set to true, domains in this account will be automatically renewed before expiration.
	AutoRenew *bool `json:"autoRenew,omitempty" url:"autoRenew,omitempty"`
	// CreateDate is the date the account was created.
	CreateDate *time.Time `json:"createDate,omitempty" url:"createDate,omitempty"`
	// Password has minimum length of 7 characters. It must contain at least 1 letter and at least 1 number/symbol.
	Password *string `json:"password,omitempty" url:"password,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (a *AccountRequest) GetContacts() *ContactsRequest {
	if a == nil {
		return nil
	}
	return a.Contacts
}

func (a *AccountRequest) GetAccountID() *int {
	if a == nil {
		return nil
	}
	return a.AccountID
}

func (a *AccountRequest) GetAccountName() *string {
	if a == nil {
		return nil
	}
	return a.AccountName
}

func (a *AccountRequest) GetAutoRenew() *bool {
	if a == nil {
		return nil
	}
	return a.AutoRenew
}

func (a *AccountRequest) GetCreateDate() *time.Time {
	if a == nil {
		return nil
	}
	return a.CreateDate
}

func (a *AccountRequest) GetPassword() *string {
	if a == nil {
		return nil
	}
	return a.Password
}

func (a *AccountRequest) GetExtraProperties() map[string]interface{} {
	if a == nil {
		return nil
	}
	return a.extraProperties
}

func (a *AccountRequest) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetContacts sets the Contacts field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AccountRequest) SetContacts(contacts *ContactsRequest) {
	a.Contacts = contacts
	a.require(accountRequestFieldContacts)
}

// SetAccountID sets the AccountID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AccountRequest) SetAccountID(accountID *int) {
	a.AccountID = accountID
	a.require(accountRequestFieldAccountID)
}

// SetAccountName sets the AccountName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AccountRequest) SetAccountName(accountName *string) {
	a.AccountName = accountName
	a.require(accountRequestFieldAccountName)
}

// SetAutoRenew sets the AutoRenew field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AccountRequest) SetAutoRenew(autoRenew *bool) {
	a.AutoRenew = autoRenew
	a.require(accountRequestFieldAutoRenew)
}

// SetCreateDate sets the CreateDate field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AccountRequest) SetCreateDate(createDate *time.Time) {
	a.CreateDate = createDate
	a.require(accountRequestFieldCreateDate)
}

// SetPassword sets the Password field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AccountRequest) SetPassword(password *string) {
	a.Password = password
	a.require(accountRequestFieldPassword)
}

func (a *AccountRequest) UnmarshalJSON(data []byte) error {
	type embed AccountRequest
	var unmarshaler = struct {
		embed
		CreateDate *internal.DateTime `json:"createDate,omitempty"`
	}{
		embed: embed(*a),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*a = AccountRequest(unmarshaler.embed)
	a.CreateDate = unmarshaler.CreateDate.TimePtr()
	extraProperties, err := internal.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties
	a.rawJSON = json.RawMessage(data)
	return nil
}

func (a *AccountRequest) MarshalJSON() ([]byte, error) {
	type embed AccountRequest
	var marshaler = struct {
		embed
		CreateDate *internal.DateTime `json:"createDate,omitempty"`
	}{
		embed:      embed(*a),
		CreateDate: internal.NewOptionalDateTime(a.CreateDate),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, a.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (a *AccountRequest) String() string {
	if a == nil {
		return "<nil>"
	}
	if len(a.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(a.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

// CreateAccountResponse contains information about the newly created account and the API credentials generated for it.
var (
	createAccountResponseFieldAccountName  = big.NewInt(1 << 0)
	createAccountResponseFieldAPIToken     = big.NewInt(1 << 1)
	createAccountResponseFieldAPITokenName = big.NewInt(1 << 2)
)

type CreateAccountResponse struct {
	// AccountName is the unique user-assigned name of newly created account.
	AccountName string `json:"accountName" url:"accountName"`
	// The authentication token that should be used to access the API. This value is only returned once upon account creation.
	APIToken string `json:"apiToken" url:"apiToken"`
	// ApiTokenName user assigned name of api token.
	APITokenName string `json:"apiTokenName" url:"apiTokenName"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CreateAccountResponse) GetAccountName() string {
	if c == nil {
		return ""
	}
	return c.AccountName
}

func (c *CreateAccountResponse) GetAPIToken() string {
	if c == nil {
		return ""
	}
	return c.APIToken
}

func (c *CreateAccountResponse) GetAPITokenName() string {
	if c == nil {
		return ""
	}
	return c.APITokenName
}

func (c *CreateAccountResponse) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CreateAccountResponse) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetAccountName sets the AccountName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateAccountResponse) SetAccountName(accountName string) {
	c.AccountName = accountName
	c.require(createAccountResponseFieldAccountName)
}

// SetAPIToken sets the APIToken field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateAccountResponse) SetAPIToken(apiToken string) {
	c.APIToken = apiToken
	c.require(createAccountResponseFieldAPIToken)
}

// SetAPITokenName sets the APITokenName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateAccountResponse) SetAPITokenName(apiTokenName string) {
	c.APITokenName = apiTokenName
	c.require(createAccountResponseFieldAPITokenName)
}

func (c *CreateAccountResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateAccountResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreateAccountResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreateAccountResponse) MarshalJSON() ([]byte, error) {
	type embed CreateAccountResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CreateAccountResponse) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}
