// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	assert "github.com/stretchr/testify/assert"
	require "github.com/stretchr/testify/require"
	testing "testing"
	time "time"
)

func TestSettersResendContactVerificationEmailRequest(t *testing.T) {
	t.Run("SetVerificationID", func(t *testing.T) {
		obj := &ResendContactVerificationEmailRequest{}
		var fernTestValueVerificationID int
		obj.SetVerificationID(fernTestValueVerificationID)
		assert.Equal(t, fernTestValueVerificationID, obj.VerificationID)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitResendContactVerificationEmailRequest(t *testing.T) {
	t.Run("SetVerificationID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ResendContactVerificationEmailRequest{}
		var fernTestValueVerificationID int

		// Act
		obj.SetVerificationID(fernTestValueVerificationID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersUnverifiedContactsListRequest(t *testing.T) {
	t.Run("SetPerPage", func(t *testing.T) {
		obj := &UnverifiedContactsListRequest{}
		var fernTestValuePerPage *int
		obj.SetPerPage(fernTestValuePerPage)
		assert.Equal(t, fernTestValuePerPage, obj.PerPage)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPage", func(t *testing.T) {
		obj := &UnverifiedContactsListRequest{}
		var fernTestValuePage *int
		obj.SetPage(fernTestValuePage)
		assert.Equal(t, fernTestValuePage, obj.Page)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitUnverifiedContactsListRequest(t *testing.T) {
	t.Run("SetPerPage_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UnverifiedContactsListRequest{}
		var fernTestValuePerPage *int

		// Act
		obj.SetPerPage(fernTestValuePerPage)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPage_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UnverifiedContactsListRequest{}
		var fernTestValuePage *int

		// Act
		obj.SetPage(fernTestValuePage)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersVerifyContactRequest(t *testing.T) {
	t.Run("SetVerificationID", func(t *testing.T) {
		obj := &VerifyContactRequest{}
		var fernTestValueVerificationID int
		obj.SetVerificationID(fernTestValueVerificationID)
		assert.Equal(t, fernTestValueVerificationID, obj.VerificationID)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitVerifyContactRequest(t *testing.T) {
	t.Run("SetVerificationID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &VerifyContactRequest{}
		var fernTestValueVerificationID int

		// Act
		obj.SetVerificationID(fernTestValueVerificationID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersContactVerificationResendResponse(t *testing.T) {
	t.Run("SetSent", func(t *testing.T) {
		obj := &ContactVerificationResendResponse{}
		var fernTestValueSent bool
		obj.SetSent(fernTestValueSent)
		assert.Equal(t, fernTestValueSent, obj.Sent)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetVerificationID", func(t *testing.T) {
		obj := &ContactVerificationResendResponse{}
		var fernTestValueVerificationID int
		obj.SetVerificationID(fernTestValueVerificationID)
		assert.Equal(t, fernTestValueVerificationID, obj.VerificationID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetNextEligibleAt", func(t *testing.T) {
		obj := &ContactVerificationResendResponse{}
		var fernTestValueNextEligibleAt time.Time
		obj.SetNextEligibleAt(fernTestValueNextEligibleAt)
		assert.Equal(t, fernTestValueNextEligibleAt, obj.NextEligibleAt)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersContactVerificationResendResponse(t *testing.T) {
	t.Run("GetSent", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ContactVerificationResendResponse{}
		var expected bool
		obj.Sent = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetSent(), "getter should return the property value")
	})

	t.Run("GetSent_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ContactVerificationResendResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetSent() // Should return zero value
	})

	t.Run("GetVerificationID", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ContactVerificationResendResponse{}
		var expected int
		obj.VerificationID = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetVerificationID(), "getter should return the property value")
	})

	t.Run("GetVerificationID_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ContactVerificationResendResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetVerificationID() // Should return zero value
	})

	t.Run("GetNextEligibleAt", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ContactVerificationResendResponse{}
		var expected time.Time
		obj.NextEligibleAt = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetNextEligibleAt(), "getter should return the property value")
	})

	t.Run("GetNextEligibleAt_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ContactVerificationResendResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetNextEligibleAt() // Should return zero value
	})

}

func TestSettersMarkExplicitContactVerificationResendResponse(t *testing.T) {
	t.Run("SetSent_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ContactVerificationResendResponse{}
		var fernTestValueSent bool

		// Act
		obj.SetSent(fernTestValueSent)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetVerificationID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ContactVerificationResendResponse{}
		var fernTestValueVerificationID int

		// Act
		obj.SetVerificationID(fernTestValueVerificationID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetNextEligibleAt_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ContactVerificationResendResponse{}
		var fernTestValueNextEligibleAt time.Time

		// Act
		obj.SetNextEligibleAt(fernTestValueNextEligibleAt)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersUnverifiedContact(t *testing.T) {
	t.Run("SetVerificationID", func(t *testing.T) {
		obj := &UnverifiedContact{}
		var fernTestValueVerificationID int64
		obj.SetVerificationID(fernTestValueVerificationID)
		assert.Equal(t, fernTestValueVerificationID, obj.VerificationID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetCreateDate", func(t *testing.T) {
		obj := &UnverifiedContact{}
		var fernTestValueCreateDate *time.Time
		obj.SetCreateDate(fernTestValueCreateDate)
		assert.Equal(t, fernTestValueCreateDate, obj.CreateDate)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetVerifyBy", func(t *testing.T) {
		obj := &UnverifiedContact{}
		var fernTestValueVerifyBy *time.Time
		obj.SetVerifyBy(fernTestValueVerifyBy)
		assert.Equal(t, fernTestValueVerifyBy, obj.VerifyBy)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetEmail", func(t *testing.T) {
		obj := &UnverifiedContact{}
		var fernTestValueEmail *string
		obj.SetEmail(fernTestValueEmail)
		assert.Equal(t, fernTestValueEmail, obj.Email)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetDomains", func(t *testing.T) {
		obj := &UnverifiedContact{}
		var fernTestValueDomains []string
		obj.SetDomains(fernTestValueDomains)
		assert.Equal(t, fernTestValueDomains, obj.Domains)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersUnverifiedContact(t *testing.T) {
	t.Run("GetVerificationID", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UnverifiedContact{}
		var expected int64
		obj.VerificationID = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetVerificationID(), "getter should return the property value")
	})

	t.Run("GetVerificationID_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *UnverifiedContact
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetVerificationID() // Should return zero value
	})

	t.Run("GetCreateDate", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UnverifiedContact{}
		var expected *time.Time
		obj.CreateDate = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetCreateDate(), "getter should return the property value")
	})

	t.Run("GetCreateDate_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UnverifiedContact{}
		obj.CreateDate = nil

		// Act & Assert
		assert.Nil(t, obj.GetCreateDate(), "getter should return nil when property is nil")
	})

	t.Run("GetCreateDate_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *UnverifiedContact
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetCreateDate() // Should return zero value
	})

	t.Run("GetVerifyBy", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UnverifiedContact{}
		var expected *time.Time
		obj.VerifyBy = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetVerifyBy(), "getter should return the property value")
	})

	t.Run("GetVerifyBy_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UnverifiedContact{}
		obj.VerifyBy = nil

		// Act & Assert
		assert.Nil(t, obj.GetVerifyBy(), "getter should return nil when property is nil")
	})

	t.Run("GetVerifyBy_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *UnverifiedContact
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetVerifyBy() // Should return zero value
	})

	t.Run("GetEmail", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UnverifiedContact{}
		var expected *string
		obj.Email = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetEmail(), "getter should return the property value")
	})

	t.Run("GetEmail_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UnverifiedContact{}
		obj.Email = nil

		// Act & Assert
		assert.Nil(t, obj.GetEmail(), "getter should return nil when property is nil")
	})

	t.Run("GetEmail_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *UnverifiedContact
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetEmail() // Should return zero value
	})

	t.Run("GetDomains", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UnverifiedContact{}
		var expected []string
		obj.Domains = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetDomains(), "getter should return the property value")
	})

	t.Run("GetDomains_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UnverifiedContact{}
		obj.Domains = nil

		// Act & Assert
		assert.Nil(t, obj.GetDomains(), "getter should return nil when property is nil")
	})

	t.Run("GetDomains_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *UnverifiedContact
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetDomains() // Should return zero value
	})

}

func TestSettersMarkExplicitUnverifiedContact(t *testing.T) {
	t.Run("SetVerificationID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UnverifiedContact{}
		var fernTestValueVerificationID int64

		// Act
		obj.SetVerificationID(fernTestValueVerificationID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetCreateDate_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UnverifiedContact{}
		var fernTestValueCreateDate *time.Time

		// Act
		obj.SetCreateDate(fernTestValueCreateDate)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetVerifyBy_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UnverifiedContact{}
		var fernTestValueVerifyBy *time.Time

		// Act
		obj.SetVerifyBy(fernTestValueVerifyBy)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetEmail_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UnverifiedContact{}
		var fernTestValueEmail *string

		// Act
		obj.SetEmail(fernTestValueEmail)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetDomains_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UnverifiedContact{}
		var fernTestValueDomains []string

		// Act
		obj.SetDomains(fernTestValueDomains)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersUnverifiedContactsResponse(t *testing.T) {
	t.Run("SetUnverifiedContacts", func(t *testing.T) {
		obj := &UnverifiedContactsResponse{}
		var fernTestValueUnverifiedContacts []*UnverifiedContact
		obj.SetUnverifiedContacts(fernTestValueUnverifiedContacts)
		assert.Equal(t, fernTestValueUnverifiedContacts, obj.UnverifiedContacts)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetFrom", func(t *testing.T) {
		obj := &UnverifiedContactsResponse{}
		var fernTestValueFrom int
		obj.SetFrom(fernTestValueFrom)
		assert.Equal(t, fernTestValueFrom, obj.From)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetTo", func(t *testing.T) {
		obj := &UnverifiedContactsResponse{}
		var fernTestValueTo int
		obj.SetTo(fernTestValueTo)
		assert.Equal(t, fernTestValueTo, obj.To)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetLastPage", func(t *testing.T) {
		obj := &UnverifiedContactsResponse{}
		var fernTestValueLastPage int
		obj.SetLastPage(fernTestValueLastPage)
		assert.Equal(t, fernTestValueLastPage, obj.LastPage)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetNextPage", func(t *testing.T) {
		obj := &UnverifiedContactsResponse{}
		var fernTestValueNextPage *int
		obj.SetNextPage(fernTestValueNextPage)
		assert.Equal(t, fernTestValueNextPage, obj.NextPage)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetTotalCount", func(t *testing.T) {
		obj := &UnverifiedContactsResponse{}
		var fernTestValueTotalCount int
		obj.SetTotalCount(fernTestValueTotalCount)
		assert.Equal(t, fernTestValueTotalCount, obj.TotalCount)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersUnverifiedContactsResponse(t *testing.T) {
	t.Run("GetUnverifiedContacts", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UnverifiedContactsResponse{}
		var expected []*UnverifiedContact
		obj.UnverifiedContacts = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetUnverifiedContacts(), "getter should return the property value")
	})

	t.Run("GetUnverifiedContacts_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UnverifiedContactsResponse{}
		obj.UnverifiedContacts = nil

		// Act & Assert
		assert.Nil(t, obj.GetUnverifiedContacts(), "getter should return nil when property is nil")
	})

	t.Run("GetUnverifiedContacts_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *UnverifiedContactsResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetUnverifiedContacts() // Should return zero value
	})

	t.Run("GetFrom", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UnverifiedContactsResponse{}
		var expected int
		obj.From = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetFrom(), "getter should return the property value")
	})

	t.Run("GetFrom_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *UnverifiedContactsResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetFrom() // Should return zero value
	})

	t.Run("GetTo", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UnverifiedContactsResponse{}
		var expected int
		obj.To = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetTo(), "getter should return the property value")
	})

	t.Run("GetTo_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *UnverifiedContactsResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetTo() // Should return zero value
	})

	t.Run("GetLastPage", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UnverifiedContactsResponse{}
		var expected int
		obj.LastPage = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetLastPage(), "getter should return the property value")
	})

	t.Run("GetLastPage_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *UnverifiedContactsResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetLastPage() // Should return zero value
	})

	t.Run("GetNextPage", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UnverifiedContactsResponse{}
		var expected *int
		obj.NextPage = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetNextPage(), "getter should return the property value")
	})

	t.Run("GetNextPage_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UnverifiedContactsResponse{}
		obj.NextPage = nil

		// Act & Assert
		assert.Nil(t, obj.GetNextPage(), "getter should return nil when property is nil")
	})

	t.Run("GetNextPage_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *UnverifiedContactsResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetNextPage() // Should return zero value
	})

	t.Run("GetTotalCount", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UnverifiedContactsResponse{}
		var expected int
		obj.TotalCount = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetTotalCount(), "getter should return the property value")
	})

	t.Run("GetTotalCount_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *UnverifiedContactsResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetTotalCount() // Should return zero value
	})

}

func TestSettersMarkExplicitUnverifiedContactsResponse(t *testing.T) {
	t.Run("SetUnverifiedContacts_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UnverifiedContactsResponse{}
		var fernTestValueUnverifiedContacts []*UnverifiedContact

		// Act
		obj.SetUnverifiedContacts(fernTestValueUnverifiedContacts)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetFrom_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UnverifiedContactsResponse{}
		var fernTestValueFrom int

		// Act
		obj.SetFrom(fernTestValueFrom)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetTo_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UnverifiedContactsResponse{}
		var fernTestValueTo int

		// Act
		obj.SetTo(fernTestValueTo)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetLastPage_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UnverifiedContactsResponse{}
		var fernTestValueLastPage int

		// Act
		obj.SetLastPage(fernTestValueLastPage)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetNextPage_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UnverifiedContactsResponse{}
		var fernTestValueNextPage *int

		// Act
		obj.SetNextPage(fernTestValueNextPage)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetTotalCount_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UnverifiedContactsResponse{}
		var fernTestValueTotalCount int

		// Act
		obj.SetTotalCount(fernTestValueTotalCount)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestJSONMarshalingContactVerificationResendResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ContactVerificationResendResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled ContactVerificationResendResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj ContactVerificationResendResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj ContactVerificationResendResponse
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingUnverifiedContact(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UnverifiedContact{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled UnverifiedContact
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj UnverifiedContact
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj UnverifiedContact
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingUnverifiedContactsResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UnverifiedContactsResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled UnverifiedContactsResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj UnverifiedContactsResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj UnverifiedContactsResponse
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestStringContactVerificationResendResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &ContactVerificationResendResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ContactVerificationResendResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringUnverifiedContact(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &UnverifiedContact{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *UnverifiedContact
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringUnverifiedContactsResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &UnverifiedContactsResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *UnverifiedContactsResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestExtraPropertiesContactVerificationResendResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &ContactVerificationResendResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ContactVerificationResendResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesUnverifiedContact(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &UnverifiedContact{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *UnverifiedContact
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesUnverifiedContactsResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &UnverifiedContactsResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *UnverifiedContactsResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}
