// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	assert "github.com/stretchr/testify/assert"
	require "github.com/stretchr/testify/require"
	testing "testing"
)

func TestSettersDNSCreateRecordBody(t *testing.T) {
	t.Run("SetDomainName", func(t *testing.T) {
		obj := &DNSCreateRecordBody{}
		var fernTestValueDomainName string
		obj.SetDomainName(fernTestValueDomainName)
		assert.Equal(t, fernTestValueDomainName, obj.DomainName)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetAnswer", func(t *testing.T) {
		obj := &DNSCreateRecordBody{}
		var fernTestValueAnswer string
		obj.SetAnswer(fernTestValueAnswer)
		assert.Equal(t, fernTestValueAnswer, obj.Answer)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetFqdn", func(t *testing.T) {
		obj := &DNSCreateRecordBody{}
		var fernTestValueFqdn *string
		obj.SetFqdn(fernTestValueFqdn)
		assert.Equal(t, fernTestValueFqdn, obj.Fqdn)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetHost", func(t *testing.T) {
		obj := &DNSCreateRecordBody{}
		var fernTestValueHost string
		obj.SetHost(fernTestValueHost)
		assert.Equal(t, fernTestValueHost, obj.Host)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetID", func(t *testing.T) {
		obj := &DNSCreateRecordBody{}
		var fernTestValueID *int
		obj.SetID(fernTestValueID)
		assert.Equal(t, fernTestValueID, obj.ID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPriority", func(t *testing.T) {
		obj := &DNSCreateRecordBody{}
		var fernTestValuePriority *int64
		obj.SetPriority(fernTestValuePriority)
		assert.Equal(t, fernTestValuePriority, obj.Priority)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetTTL", func(t *testing.T) {
		obj := &DNSCreateRecordBody{}
		var fernTestValueTTL *int64
		obj.SetTTL(fernTestValueTTL)
		assert.Equal(t, fernTestValueTTL, obj.TTL)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetType", func(t *testing.T) {
		obj := &DNSCreateRecordBody{}
		var fernTestValueType DNSCreateRecordBodyType
		obj.SetType(fernTestValueType)
		assert.Equal(t, fernTestValueType, obj.Type)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitDNSCreateRecordBody(t *testing.T) {
	t.Run("SetDomainName_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DNSCreateRecordBody{}
		var fernTestValueDomainName string

		// Act
		obj.SetDomainName(fernTestValueDomainName)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetAnswer_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DNSCreateRecordBody{}
		var fernTestValueAnswer string

		// Act
		obj.SetAnswer(fernTestValueAnswer)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetFqdn_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DNSCreateRecordBody{}
		var fernTestValueFqdn *string

		// Act
		obj.SetFqdn(fernTestValueFqdn)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetHost_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DNSCreateRecordBody{}
		var fernTestValueHost string

		// Act
		obj.SetHost(fernTestValueHost)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DNSCreateRecordBody{}
		var fernTestValueID *int

		// Act
		obj.SetID(fernTestValueID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPriority_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DNSCreateRecordBody{}
		var fernTestValuePriority *int64

		// Act
		obj.SetPriority(fernTestValuePriority)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetTTL_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DNSCreateRecordBody{}
		var fernTestValueTTL *int64

		// Act
		obj.SetTTL(fernTestValueTTL)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetType_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DNSCreateRecordBody{}
		var fernTestValueType DNSCreateRecordBodyType

		// Act
		obj.SetType(fernTestValueType)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersDeleteRecordRequest(t *testing.T) {
	t.Run("SetDomainName", func(t *testing.T) {
		obj := &DeleteRecordRequest{}
		var fernTestValueDomainName string
		obj.SetDomainName(fernTestValueDomainName)
		assert.Equal(t, fernTestValueDomainName, obj.DomainName)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetID", func(t *testing.T) {
		obj := &DeleteRecordRequest{}
		var fernTestValueID int
		obj.SetID(fernTestValueID)
		assert.Equal(t, fernTestValueID, obj.ID)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitDeleteRecordRequest(t *testing.T) {
	t.Run("SetDomainName_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DeleteRecordRequest{}
		var fernTestValueDomainName string

		// Act
		obj.SetDomainName(fernTestValueDomainName)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DeleteRecordRequest{}
		var fernTestValueID int

		// Act
		obj.SetID(fernTestValueID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersGetRecordRequest(t *testing.T) {
	t.Run("SetDomainName", func(t *testing.T) {
		obj := &GetRecordRequest{}
		var fernTestValueDomainName string
		obj.SetDomainName(fernTestValueDomainName)
		assert.Equal(t, fernTestValueDomainName, obj.DomainName)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetID", func(t *testing.T) {
		obj := &GetRecordRequest{}
		var fernTestValueID int
		obj.SetID(fernTestValueID)
		assert.Equal(t, fernTestValueID, obj.ID)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitGetRecordRequest(t *testing.T) {
	t.Run("SetDomainName_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetRecordRequest{}
		var fernTestValueDomainName string

		// Act
		obj.SetDomainName(fernTestValueDomainName)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetRecordRequest{}
		var fernTestValueID int

		// Act
		obj.SetID(fernTestValueID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersListRecordsRequest(t *testing.T) {
	t.Run("SetDomainName", func(t *testing.T) {
		obj := &ListRecordsRequest{}
		var fernTestValueDomainName string
		obj.SetDomainName(fernTestValueDomainName)
		assert.Equal(t, fernTestValueDomainName, obj.DomainName)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPerPage", func(t *testing.T) {
		obj := &ListRecordsRequest{}
		var fernTestValuePerPage *int
		obj.SetPerPage(fernTestValuePerPage)
		assert.Equal(t, fernTestValuePerPage, obj.PerPage)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPage", func(t *testing.T) {
		obj := &ListRecordsRequest{}
		var fernTestValuePage *int
		obj.SetPage(fernTestValuePage)
		assert.Equal(t, fernTestValuePage, obj.Page)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitListRecordsRequest(t *testing.T) {
	t.Run("SetDomainName_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListRecordsRequest{}
		var fernTestValueDomainName string

		// Act
		obj.SetDomainName(fernTestValueDomainName)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPerPage_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListRecordsRequest{}
		var fernTestValuePerPage *int

		// Act
		obj.SetPerPage(fernTestValuePerPage)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPage_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListRecordsRequest{}
		var fernTestValuePage *int

		// Act
		obj.SetPage(fernTestValuePage)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersDNSUpdateRecordBody(t *testing.T) {
	t.Run("SetDomainName", func(t *testing.T) {
		obj := &DNSUpdateRecordBody{}
		var fernTestValueDomainName string
		obj.SetDomainName(fernTestValueDomainName)
		assert.Equal(t, fernTestValueDomainName, obj.DomainName)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetID", func(t *testing.T) {
		obj := &DNSUpdateRecordBody{}
		var fernTestValueID int
		obj.SetID(fernTestValueID)
		assert.Equal(t, fernTestValueID, obj.ID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetAnswer", func(t *testing.T) {
		obj := &DNSUpdateRecordBody{}
		var fernTestValueAnswer string
		obj.SetAnswer(fernTestValueAnswer)
		assert.Equal(t, fernTestValueAnswer, obj.Answer)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetFqdn", func(t *testing.T) {
		obj := &DNSUpdateRecordBody{}
		var fernTestValueFqdn *string
		obj.SetFqdn(fernTestValueFqdn)
		assert.Equal(t, fernTestValueFqdn, obj.Fqdn)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetHost", func(t *testing.T) {
		obj := &DNSUpdateRecordBody{}
		var fernTestValueHost *string
		obj.SetHost(fernTestValueHost)
		assert.Equal(t, fernTestValueHost, obj.Host)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPriority", func(t *testing.T) {
		obj := &DNSUpdateRecordBody{}
		var fernTestValuePriority *int64
		obj.SetPriority(fernTestValuePriority)
		assert.Equal(t, fernTestValuePriority, obj.Priority)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetTTL", func(t *testing.T) {
		obj := &DNSUpdateRecordBody{}
		var fernTestValueTTL *int64
		obj.SetTTL(fernTestValueTTL)
		assert.Equal(t, fernTestValueTTL, obj.TTL)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetType", func(t *testing.T) {
		obj := &DNSUpdateRecordBody{}
		var fernTestValueType DNSUpdateRecordBodyType
		obj.SetType(fernTestValueType)
		assert.Equal(t, fernTestValueType, obj.Type)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitDNSUpdateRecordBody(t *testing.T) {
	t.Run("SetDomainName_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DNSUpdateRecordBody{}
		var fernTestValueDomainName string

		// Act
		obj.SetDomainName(fernTestValueDomainName)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DNSUpdateRecordBody{}
		var fernTestValueID int

		// Act
		obj.SetID(fernTestValueID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetAnswer_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DNSUpdateRecordBody{}
		var fernTestValueAnswer string

		// Act
		obj.SetAnswer(fernTestValueAnswer)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetFqdn_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DNSUpdateRecordBody{}
		var fernTestValueFqdn *string

		// Act
		obj.SetFqdn(fernTestValueFqdn)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetHost_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DNSUpdateRecordBody{}
		var fernTestValueHost *string

		// Act
		obj.SetHost(fernTestValueHost)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPriority_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DNSUpdateRecordBody{}
		var fernTestValuePriority *int64

		// Act
		obj.SetPriority(fernTestValuePriority)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetTTL_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DNSUpdateRecordBody{}
		var fernTestValueTTL *int64

		// Act
		obj.SetTTL(fernTestValueTTL)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetType_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DNSUpdateRecordBody{}
		var fernTestValueType DNSUpdateRecordBodyType

		// Act
		obj.SetType(fernTestValueType)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersListRecordsResponse(t *testing.T) {
	t.Run("SetLastPage", func(t *testing.T) {
		obj := &ListRecordsResponse{}
		var fernTestValueLastPage *int
		obj.SetLastPage(fernTestValueLastPage)
		assert.Equal(t, fernTestValueLastPage, obj.LastPage)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetNextPage", func(t *testing.T) {
		obj := &ListRecordsResponse{}
		var fernTestValueNextPage *int
		obj.SetNextPage(fernTestValueNextPage)
		assert.Equal(t, fernTestValueNextPage, obj.NextPage)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetTotalCount", func(t *testing.T) {
		obj := &ListRecordsResponse{}
		var fernTestValueTotalCount int
		obj.SetTotalCount(fernTestValueTotalCount)
		assert.Equal(t, fernTestValueTotalCount, obj.TotalCount)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetFrom", func(t *testing.T) {
		obj := &ListRecordsResponse{}
		var fernTestValueFrom int
		obj.SetFrom(fernTestValueFrom)
		assert.Equal(t, fernTestValueFrom, obj.From)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetTo", func(t *testing.T) {
		obj := &ListRecordsResponse{}
		var fernTestValueTo int
		obj.SetTo(fernTestValueTo)
		assert.Equal(t, fernTestValueTo, obj.To)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetRecords", func(t *testing.T) {
		obj := &ListRecordsResponse{}
		var fernTestValueRecords []*Record
		obj.SetRecords(fernTestValueRecords)
		assert.Equal(t, fernTestValueRecords, obj.Records)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersListRecordsResponse(t *testing.T) {
	t.Run("GetLastPage", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListRecordsResponse{}
		var expected *int
		obj.LastPage = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetLastPage(), "getter should return the property value")
	})

	t.Run("GetLastPage_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListRecordsResponse{}
		obj.LastPage = nil

		// Act & Assert
		assert.Nil(t, obj.GetLastPage(), "getter should return nil when property is nil")
	})

	t.Run("GetLastPage_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListRecordsResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetLastPage() // Should return zero value
	})

	t.Run("GetNextPage", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListRecordsResponse{}
		var expected *int
		obj.NextPage = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetNextPage(), "getter should return the property value")
	})

	t.Run("GetNextPage_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListRecordsResponse{}
		obj.NextPage = nil

		// Act & Assert
		assert.Nil(t, obj.GetNextPage(), "getter should return nil when property is nil")
	})

	t.Run("GetNextPage_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListRecordsResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetNextPage() // Should return zero value
	})

	t.Run("GetTotalCount", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListRecordsResponse{}
		var expected int
		obj.TotalCount = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetTotalCount(), "getter should return the property value")
	})

	t.Run("GetTotalCount_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListRecordsResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetTotalCount() // Should return zero value
	})

	t.Run("GetFrom", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListRecordsResponse{}
		var expected int
		obj.From = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetFrom(), "getter should return the property value")
	})

	t.Run("GetFrom_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListRecordsResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetFrom() // Should return zero value
	})

	t.Run("GetTo", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListRecordsResponse{}
		var expected int
		obj.To = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetTo(), "getter should return the property value")
	})

	t.Run("GetTo_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListRecordsResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetTo() // Should return zero value
	})

	t.Run("GetRecords", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListRecordsResponse{}
		var expected []*Record
		obj.Records = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetRecords(), "getter should return the property value")
	})

	t.Run("GetRecords_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListRecordsResponse{}
		obj.Records = nil

		// Act & Assert
		assert.Nil(t, obj.GetRecords(), "getter should return nil when property is nil")
	})

	t.Run("GetRecords_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListRecordsResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetRecords() // Should return zero value
	})

}

func TestSettersMarkExplicitListRecordsResponse(t *testing.T) {
	t.Run("SetLastPage_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListRecordsResponse{}
		var fernTestValueLastPage *int

		// Act
		obj.SetLastPage(fernTestValueLastPage)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetNextPage_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListRecordsResponse{}
		var fernTestValueNextPage *int

		// Act
		obj.SetNextPage(fernTestValueNextPage)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetTotalCount_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListRecordsResponse{}
		var fernTestValueTotalCount int

		// Act
		obj.SetTotalCount(fernTestValueTotalCount)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetFrom_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListRecordsResponse{}
		var fernTestValueFrom int

		// Act
		obj.SetFrom(fernTestValueFrom)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetTo_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListRecordsResponse{}
		var fernTestValueTo int

		// Act
		obj.SetTo(fernTestValueTo)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetRecords_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListRecordsResponse{}
		var fernTestValueRecords []*Record

		// Act
		obj.SetRecords(fernTestValueRecords)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersRecord(t *testing.T) {
	t.Run("SetAnswer", func(t *testing.T) {
		obj := &Record{}
		var fernTestValueAnswer *string
		obj.SetAnswer(fernTestValueAnswer)
		assert.Equal(t, fernTestValueAnswer, obj.Answer)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetDomainName", func(t *testing.T) {
		obj := &Record{}
		var fernTestValueDomainName *string
		obj.SetDomainName(fernTestValueDomainName)
		assert.Equal(t, fernTestValueDomainName, obj.DomainName)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetFqdn", func(t *testing.T) {
		obj := &Record{}
		var fernTestValueFqdn *string
		obj.SetFqdn(fernTestValueFqdn)
		assert.Equal(t, fernTestValueFqdn, obj.Fqdn)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetHost", func(t *testing.T) {
		obj := &Record{}
		var fernTestValueHost *string
		obj.SetHost(fernTestValueHost)
		assert.Equal(t, fernTestValueHost, obj.Host)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetID", func(t *testing.T) {
		obj := &Record{}
		var fernTestValueID *int
		obj.SetID(fernTestValueID)
		assert.Equal(t, fernTestValueID, obj.ID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPriority", func(t *testing.T) {
		obj := &Record{}
		var fernTestValuePriority *int64
		obj.SetPriority(fernTestValuePriority)
		assert.Equal(t, fernTestValuePriority, obj.Priority)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetTTL", func(t *testing.T) {
		obj := &Record{}
		var fernTestValueTTL int64
		obj.SetTTL(fernTestValueTTL)
		assert.Equal(t, fernTestValueTTL, obj.TTL)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetType", func(t *testing.T) {
		obj := &Record{}
		var fernTestValueType *string
		obj.SetType(fernTestValueType)
		assert.Equal(t, fernTestValueType, obj.Type)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersRecord(t *testing.T) {
	t.Run("GetAnswer", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Record{}
		var expected *string
		obj.Answer = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetAnswer(), "getter should return the property value")
	})

	t.Run("GetAnswer_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Record{}
		obj.Answer = nil

		// Act & Assert
		assert.Nil(t, obj.GetAnswer(), "getter should return nil when property is nil")
	})

	t.Run("GetAnswer_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Record
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetAnswer() // Should return zero value
	})

	t.Run("GetDomainName", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Record{}
		var expected *string
		obj.DomainName = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetDomainName(), "getter should return the property value")
	})

	t.Run("GetDomainName_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Record{}
		obj.DomainName = nil

		// Act & Assert
		assert.Nil(t, obj.GetDomainName(), "getter should return nil when property is nil")
	})

	t.Run("GetDomainName_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Record
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetDomainName() // Should return zero value
	})

	t.Run("GetFqdn", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Record{}
		var expected *string
		obj.Fqdn = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetFqdn(), "getter should return the property value")
	})

	t.Run("GetFqdn_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Record{}
		obj.Fqdn = nil

		// Act & Assert
		assert.Nil(t, obj.GetFqdn(), "getter should return nil when property is nil")
	})

	t.Run("GetFqdn_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Record
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetFqdn() // Should return zero value
	})

	t.Run("GetHost", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Record{}
		var expected *string
		obj.Host = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetHost(), "getter should return the property value")
	})

	t.Run("GetHost_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Record{}
		obj.Host = nil

		// Act & Assert
		assert.Nil(t, obj.GetHost(), "getter should return nil when property is nil")
	})

	t.Run("GetHost_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Record
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetHost() // Should return zero value
	})

	t.Run("GetID", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Record{}
		var expected *int
		obj.ID = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetID(), "getter should return the property value")
	})

	t.Run("GetID_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Record{}
		obj.ID = nil

		// Act & Assert
		assert.Nil(t, obj.GetID(), "getter should return nil when property is nil")
	})

	t.Run("GetID_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Record
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetID() // Should return zero value
	})

	t.Run("GetPriority", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Record{}
		var expected *int64
		obj.Priority = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetPriority(), "getter should return the property value")
	})

	t.Run("GetPriority_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Record{}
		obj.Priority = nil

		// Act & Assert
		assert.Nil(t, obj.GetPriority(), "getter should return nil when property is nil")
	})

	t.Run("GetPriority_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Record
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetPriority() // Should return zero value
	})

	t.Run("GetTTL", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Record{}
		var expected int64
		obj.TTL = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetTTL(), "getter should return the property value")
	})

	t.Run("GetTTL_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Record
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetTTL() // Should return zero value
	})

	t.Run("GetType", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Record{}
		var expected *string
		obj.Type = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetType(), "getter should return the property value")
	})

	t.Run("GetType_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Record{}
		obj.Type = nil

		// Act & Assert
		assert.Nil(t, obj.GetType(), "getter should return nil when property is nil")
	})

	t.Run("GetType_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Record
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetType() // Should return zero value
	})

}

func TestSettersMarkExplicitRecord(t *testing.T) {
	t.Run("SetAnswer_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Record{}
		var fernTestValueAnswer *string

		// Act
		obj.SetAnswer(fernTestValueAnswer)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetDomainName_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Record{}
		var fernTestValueDomainName *string

		// Act
		obj.SetDomainName(fernTestValueDomainName)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetFqdn_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Record{}
		var fernTestValueFqdn *string

		// Act
		obj.SetFqdn(fernTestValueFqdn)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetHost_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Record{}
		var fernTestValueHost *string

		// Act
		obj.SetHost(fernTestValueHost)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Record{}
		var fernTestValueID *int

		// Act
		obj.SetID(fernTestValueID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPriority_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Record{}
		var fernTestValuePriority *int64

		// Act
		obj.SetPriority(fernTestValuePriority)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetTTL_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Record{}
		var fernTestValueTTL int64

		// Act
		obj.SetTTL(fernTestValueTTL)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetType_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Record{}
		var fernTestValueType *string

		// Act
		obj.SetType(fernTestValueType)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestJSONMarshalingListRecordsResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListRecordsResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled ListRecordsResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj ListRecordsResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj ListRecordsResponse
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingRecord(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Record{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled Record
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj Record
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj Record
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestStringListRecordsResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &ListRecordsResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListRecordsResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringRecord(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &Record{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Record
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestEnumDNSCreateRecordBodyType(t *testing.T) {
	t.Run("NewFromString_A", func(t *testing.T) {
		t.Parallel()
		val, err := NewDNSCreateRecordBodyTypeFromString("A")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, DNSCreateRecordBodyType("A"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_AAAA", func(t *testing.T) {
		t.Parallel()
		val, err := NewDNSCreateRecordBodyTypeFromString("AAAA")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, DNSCreateRecordBodyType("AAAA"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_ANAME", func(t *testing.T) {
		t.Parallel()
		val, err := NewDNSCreateRecordBodyTypeFromString("ANAME")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, DNSCreateRecordBodyType("ANAME"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_CNAME", func(t *testing.T) {
		t.Parallel()
		val, err := NewDNSCreateRecordBodyTypeFromString("CNAME")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, DNSCreateRecordBodyType("CNAME"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_MX", func(t *testing.T) {
		t.Parallel()
		val, err := NewDNSCreateRecordBodyTypeFromString("MX")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, DNSCreateRecordBodyType("MX"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_NS", func(t *testing.T) {
		t.Parallel()
		val, err := NewDNSCreateRecordBodyTypeFromString("NS")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, DNSCreateRecordBodyType("NS"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_SRV", func(t *testing.T) {
		t.Parallel()
		val, err := NewDNSCreateRecordBodyTypeFromString("SRV")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, DNSCreateRecordBodyType("SRV"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_TXT", func(t *testing.T) {
		t.Parallel()
		val, err := NewDNSCreateRecordBodyTypeFromString("TXT")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, DNSCreateRecordBodyType("TXT"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_Invalid", func(t *testing.T) {
		_, err := NewDNSCreateRecordBodyTypeFromString("invalid_value_that_does_not_exist")
		assert.Error(t, err)
	})

	t.Run("Ptr", func(t *testing.T) {
		val, err := NewDNSCreateRecordBodyTypeFromString("A")
		assert.NoError(t, err)
		ptr := val.Ptr()
		assert.NotNil(t, ptr)
		assert.Equal(t, val, *ptr)
	})
}

func TestEnumDNSUpdateRecordBodyType(t *testing.T) {
	t.Run("NewFromString_A", func(t *testing.T) {
		t.Parallel()
		val, err := NewDNSUpdateRecordBodyTypeFromString("A")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, DNSUpdateRecordBodyType("A"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_AAAA", func(t *testing.T) {
		t.Parallel()
		val, err := NewDNSUpdateRecordBodyTypeFromString("AAAA")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, DNSUpdateRecordBodyType("AAAA"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_ANAME", func(t *testing.T) {
		t.Parallel()
		val, err := NewDNSUpdateRecordBodyTypeFromString("ANAME")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, DNSUpdateRecordBodyType("ANAME"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_CNAME", func(t *testing.T) {
		t.Parallel()
		val, err := NewDNSUpdateRecordBodyTypeFromString("CNAME")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, DNSUpdateRecordBodyType("CNAME"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_MX", func(t *testing.T) {
		t.Parallel()
		val, err := NewDNSUpdateRecordBodyTypeFromString("MX")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, DNSUpdateRecordBodyType("MX"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_NS", func(t *testing.T) {
		t.Parallel()
		val, err := NewDNSUpdateRecordBodyTypeFromString("NS")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, DNSUpdateRecordBodyType("NS"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_SRV", func(t *testing.T) {
		t.Parallel()
		val, err := NewDNSUpdateRecordBodyTypeFromString("SRV")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, DNSUpdateRecordBodyType("SRV"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_TXT", func(t *testing.T) {
		t.Parallel()
		val, err := NewDNSUpdateRecordBodyTypeFromString("TXT")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, DNSUpdateRecordBodyType("TXT"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_Invalid", func(t *testing.T) {
		_, err := NewDNSUpdateRecordBodyTypeFromString("invalid_value_that_does_not_exist")
		assert.Error(t, err)
	})

	t.Run("Ptr", func(t *testing.T) {
		val, err := NewDNSUpdateRecordBodyTypeFromString("A")
		assert.NoError(t, err)
		ptr := val.Ptr()
		assert.NotNil(t, ptr)
		assert.Equal(t, val, *ptr)
	})
}

func TestExtraPropertiesListRecordsResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &ListRecordsResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListRecordsResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesRecord(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &Record{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Record
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}
