// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	assert "github.com/stretchr/testify/assert"
	require "github.com/stretchr/testify/require"
	testing "testing"
)

func TestSettersCreateDnssecBody(t *testing.T) {
	t.Run("SetDomainName", func(t *testing.T) {
		obj := &CreateDnssecBody{}
		var fernTestValueDomainName string
		obj.SetDomainName(fernTestValueDomainName)
		assert.Equal(t, fernTestValueDomainName, obj.DomainName)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetAlgorithm", func(t *testing.T) {
		obj := &CreateDnssecBody{}
		var fernTestValueAlgorithm *int
		obj.SetAlgorithm(fernTestValueAlgorithm)
		assert.Equal(t, fernTestValueAlgorithm, obj.Algorithm)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetDigest", func(t *testing.T) {
		obj := &CreateDnssecBody{}
		var fernTestValueDigest *string
		obj.SetDigest(fernTestValueDigest)
		assert.Equal(t, fernTestValueDigest, obj.Digest)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetCreateDnssecBodyDomainName", func(t *testing.T) {
		obj := &CreateDnssecBody{}
		var fernTestValueCreateDnssecBodyDomainName *string
		obj.SetCreateDnssecBodyDomainName(fernTestValueCreateDnssecBodyDomainName)
		assert.Equal(t, fernTestValueCreateDnssecBodyDomainName, obj.CreateDnssecBodyDomainName)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetDigestType", func(t *testing.T) {
		obj := &CreateDnssecBody{}
		var fernTestValueDigestType *int
		obj.SetDigestType(fernTestValueDigestType)
		assert.Equal(t, fernTestValueDigestType, obj.DigestType)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetKeyTag", func(t *testing.T) {
		obj := &CreateDnssecBody{}
		var fernTestValueKeyTag *int
		obj.SetKeyTag(fernTestValueKeyTag)
		assert.Equal(t, fernTestValueKeyTag, obj.KeyTag)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitCreateDnssecBody(t *testing.T) {
	t.Run("SetDomainName_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateDnssecBody{}
		var fernTestValueDomainName string

		// Act
		obj.SetDomainName(fernTestValueDomainName)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetAlgorithm_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateDnssecBody{}
		var fernTestValueAlgorithm *int

		// Act
		obj.SetAlgorithm(fernTestValueAlgorithm)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetDigest_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateDnssecBody{}
		var fernTestValueDigest *string

		// Act
		obj.SetDigest(fernTestValueDigest)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetCreateDnssecBodyDomainName_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateDnssecBody{}
		var fernTestValueCreateDnssecBodyDomainName *string

		// Act
		obj.SetCreateDnssecBodyDomainName(fernTestValueCreateDnssecBodyDomainName)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetDigestType_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateDnssecBody{}
		var fernTestValueDigestType *int

		// Act
		obj.SetDigestType(fernTestValueDigestType)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetKeyTag_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateDnssecBody{}
		var fernTestValueKeyTag *int

		// Act
		obj.SetKeyTag(fernTestValueKeyTag)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersDeleteDnssecRequest(t *testing.T) {
	t.Run("SetDomainName", func(t *testing.T) {
		obj := &DeleteDnssecRequest{}
		var fernTestValueDomainName string
		obj.SetDomainName(fernTestValueDomainName)
		assert.Equal(t, fernTestValueDomainName, obj.DomainName)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetDigest", func(t *testing.T) {
		obj := &DeleteDnssecRequest{}
		var fernTestValueDigest string
		obj.SetDigest(fernTestValueDigest)
		assert.Equal(t, fernTestValueDigest, obj.Digest)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitDeleteDnssecRequest(t *testing.T) {
	t.Run("SetDomainName_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DeleteDnssecRequest{}
		var fernTestValueDomainName string

		// Act
		obj.SetDomainName(fernTestValueDomainName)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetDigest_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DeleteDnssecRequest{}
		var fernTestValueDigest string

		// Act
		obj.SetDigest(fernTestValueDigest)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersGetDnssecRequest(t *testing.T) {
	t.Run("SetDomainName", func(t *testing.T) {
		obj := &GetDnssecRequest{}
		var fernTestValueDomainName string
		obj.SetDomainName(fernTestValueDomainName)
		assert.Equal(t, fernTestValueDomainName, obj.DomainName)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetDigest", func(t *testing.T) {
		obj := &GetDnssecRequest{}
		var fernTestValueDigest string
		obj.SetDigest(fernTestValueDigest)
		assert.Equal(t, fernTestValueDigest, obj.Digest)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitGetDnssecRequest(t *testing.T) {
	t.Run("SetDomainName_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetDnssecRequest{}
		var fernTestValueDomainName string

		// Act
		obj.SetDomainName(fernTestValueDomainName)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetDigest_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetDnssecRequest{}
		var fernTestValueDigest string

		// Act
		obj.SetDigest(fernTestValueDigest)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersListDnsseCsRequest(t *testing.T) {
	t.Run("SetDomainName", func(t *testing.T) {
		obj := &ListDnsseCsRequest{}
		var fernTestValueDomainName string
		obj.SetDomainName(fernTestValueDomainName)
		assert.Equal(t, fernTestValueDomainName, obj.DomainName)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitListDnsseCsRequest(t *testing.T) {
	t.Run("SetDomainName_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListDnsseCsRequest{}
		var fernTestValueDomainName string

		// Act
		obj.SetDomainName(fernTestValueDomainName)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersDnssec(t *testing.T) {
	t.Run("SetAlgorithm", func(t *testing.T) {
		obj := &Dnssec{}
		var fernTestValueAlgorithm int
		obj.SetAlgorithm(fernTestValueAlgorithm)
		assert.Equal(t, fernTestValueAlgorithm, obj.Algorithm)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetDigest", func(t *testing.T) {
		obj := &Dnssec{}
		var fernTestValueDigest string
		obj.SetDigest(fernTestValueDigest)
		assert.Equal(t, fernTestValueDigest, obj.Digest)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetDigestType", func(t *testing.T) {
		obj := &Dnssec{}
		var fernTestValueDigestType int
		obj.SetDigestType(fernTestValueDigestType)
		assert.Equal(t, fernTestValueDigestType, obj.DigestType)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetDomainName", func(t *testing.T) {
		obj := &Dnssec{}
		var fernTestValueDomainName string
		obj.SetDomainName(fernTestValueDomainName)
		assert.Equal(t, fernTestValueDomainName, obj.DomainName)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetKeyTag", func(t *testing.T) {
		obj := &Dnssec{}
		var fernTestValueKeyTag int
		obj.SetKeyTag(fernTestValueKeyTag)
		assert.Equal(t, fernTestValueKeyTag, obj.KeyTag)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersDnssec(t *testing.T) {
	t.Run("GetAlgorithm", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Dnssec{}
		var expected int
		obj.Algorithm = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetAlgorithm(), "getter should return the property value")
	})

	t.Run("GetAlgorithm_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Dnssec
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetAlgorithm() // Should return zero value
	})

	t.Run("GetDigest", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Dnssec{}
		var expected string
		obj.Digest = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetDigest(), "getter should return the property value")
	})

	t.Run("GetDigest_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Dnssec
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetDigest() // Should return zero value
	})

	t.Run("GetDigestType", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Dnssec{}
		var expected int
		obj.DigestType = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetDigestType(), "getter should return the property value")
	})

	t.Run("GetDigestType_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Dnssec
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetDigestType() // Should return zero value
	})

	t.Run("GetDomainName", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Dnssec{}
		var expected string
		obj.DomainName = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetDomainName(), "getter should return the property value")
	})

	t.Run("GetDomainName_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Dnssec
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetDomainName() // Should return zero value
	})

	t.Run("GetKeyTag", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Dnssec{}
		var expected int
		obj.KeyTag = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetKeyTag(), "getter should return the property value")
	})

	t.Run("GetKeyTag_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Dnssec
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetKeyTag() // Should return zero value
	})

}

func TestSettersMarkExplicitDnssec(t *testing.T) {
	t.Run("SetAlgorithm_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Dnssec{}
		var fernTestValueAlgorithm int

		// Act
		obj.SetAlgorithm(fernTestValueAlgorithm)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetDigest_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Dnssec{}
		var fernTestValueDigest string

		// Act
		obj.SetDigest(fernTestValueDigest)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetDigestType_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Dnssec{}
		var fernTestValueDigestType int

		// Act
		obj.SetDigestType(fernTestValueDigestType)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetDomainName_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Dnssec{}
		var fernTestValueDomainName string

		// Act
		obj.SetDomainName(fernTestValueDomainName)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetKeyTag_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Dnssec{}
		var fernTestValueKeyTag int

		// Act
		obj.SetKeyTag(fernTestValueKeyTag)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersListDnsseCsResponse(t *testing.T) {
	t.Run("SetDnssec", func(t *testing.T) {
		obj := &ListDnsseCsResponse{}
		var fernTestValueDnssec []*Dnssec
		obj.SetDnssec(fernTestValueDnssec)
		assert.Equal(t, fernTestValueDnssec, obj.Dnssec)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersListDnsseCsResponse(t *testing.T) {
	t.Run("GetDnssec", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListDnsseCsResponse{}
		var expected []*Dnssec
		obj.Dnssec = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetDnssec(), "getter should return the property value")
	})

	t.Run("GetDnssec_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListDnsseCsResponse{}
		obj.Dnssec = nil

		// Act & Assert
		assert.Nil(t, obj.GetDnssec(), "getter should return nil when property is nil")
	})

	t.Run("GetDnssec_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListDnsseCsResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetDnssec() // Should return zero value
	})

}

func TestSettersMarkExplicitListDnsseCsResponse(t *testing.T) {
	t.Run("SetDnssec_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListDnsseCsResponse{}
		var fernTestValueDnssec []*Dnssec

		// Act
		obj.SetDnssec(fernTestValueDnssec)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestJSONMarshalingDnssec(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Dnssec{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled Dnssec
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj Dnssec
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj Dnssec
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingListDnsseCsResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListDnsseCsResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled ListDnsseCsResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj ListDnsseCsResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj ListDnsseCsResponse
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestStringDnssec(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &Dnssec{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Dnssec
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringListDnsseCsResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &ListDnsseCsResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListDnsseCsResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestExtraPropertiesDnssec(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &Dnssec{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Dnssec
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesListDnsseCsResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &ListDnsseCsResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListDnsseCsResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}
