// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	assert "github.com/stretchr/testify/assert"
	require "github.com/stretchr/testify/require"
	testing "testing"
	time "time"
)

func TestSettersPremiumDomainsDownloadResponse(t *testing.T) {
	t.Run("SetDownloadURL", func(t *testing.T) {
		obj := &PremiumDomainsDownloadResponse{}
		var fernTestValueDownloadURL *string
		obj.SetDownloadURL(fernTestValueDownloadURL)
		assert.Equal(t, fernTestValueDownloadURL, obj.DownloadURL)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetExpireDate", func(t *testing.T) {
		obj := &PremiumDomainsDownloadResponse{}
		var fernTestValueExpireDate *time.Time
		obj.SetExpireDate(fernTestValueExpireDate)
		assert.Equal(t, fernTestValueExpireDate, obj.ExpireDate)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersPremiumDomainsDownloadResponse(t *testing.T) {
	t.Run("GetDownloadURL", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PremiumDomainsDownloadResponse{}
		var expected *string
		obj.DownloadURL = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetDownloadURL(), "getter should return the property value")
	})

	t.Run("GetDownloadURL_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PremiumDomainsDownloadResponse{}
		obj.DownloadURL = nil

		// Act & Assert
		assert.Nil(t, obj.GetDownloadURL(), "getter should return nil when property is nil")
	})

	t.Run("GetDownloadURL_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *PremiumDomainsDownloadResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetDownloadURL() // Should return zero value
	})

	t.Run("GetExpireDate", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PremiumDomainsDownloadResponse{}
		var expected *time.Time
		obj.ExpireDate = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetExpireDate(), "getter should return the property value")
	})

	t.Run("GetExpireDate_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PremiumDomainsDownloadResponse{}
		obj.ExpireDate = nil

		// Act & Assert
		assert.Nil(t, obj.GetExpireDate(), "getter should return nil when property is nil")
	})

	t.Run("GetExpireDate_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *PremiumDomainsDownloadResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetExpireDate() // Should return zero value
	})

}

func TestSettersMarkExplicitPremiumDomainsDownloadResponse(t *testing.T) {
	t.Run("SetDownloadURL_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PremiumDomainsDownloadResponse{}
		var fernTestValueDownloadURL *string

		// Act
		obj.SetDownloadURL(fernTestValueDownloadURL)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetExpireDate_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PremiumDomainsDownloadResponse{}
		var fernTestValueExpireDate *time.Time

		// Act
		obj.SetExpireDate(fernTestValueExpireDate)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestJSONMarshalingPremiumDomainsDownloadResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PremiumDomainsDownloadResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled PremiumDomainsDownloadResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj PremiumDomainsDownloadResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj PremiumDomainsDownloadResponse
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestStringPremiumDomainsDownloadResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &PremiumDomainsDownloadResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *PremiumDomainsDownloadResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestExtraPropertiesPremiumDomainsDownloadResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &PremiumDomainsDownloadResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *PremiumDomainsDownloadResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}
