// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/namedotcom/core-api-go/internal"
	big "math/big"
	time "time"
)

var (
	premiumDomainsDownloadResponseFieldDownloadURL = big.NewInt(1 << 0)
	premiumDomainsDownloadResponseFieldExpireDate  = big.NewInt(1 << 1)
)

type PremiumDomainsDownloadResponse struct {
	// The pre-signed URL to use to download the list.
	DownloadURL *string `json:"downloadUrl,omitempty" url:"downloadUrl,omitempty"`
	// The timestamp that the URL will expire.
	ExpireDate *time.Time `json:"expireDate,omitempty" url:"expireDate,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *PremiumDomainsDownloadResponse) GetDownloadURL() *string {
	if p == nil {
		return nil
	}
	return p.DownloadURL
}

func (p *PremiumDomainsDownloadResponse) GetExpireDate() *time.Time {
	if p == nil {
		return nil
	}
	return p.ExpireDate
}

func (p *PremiumDomainsDownloadResponse) GetExtraProperties() map[string]interface{} {
	if p == nil {
		return nil
	}
	return p.extraProperties
}

func (p *PremiumDomainsDownloadResponse) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetDownloadURL sets the DownloadURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PremiumDomainsDownloadResponse) SetDownloadURL(downloadURL *string) {
	p.DownloadURL = downloadURL
	p.require(premiumDomainsDownloadResponseFieldDownloadURL)
}

// SetExpireDate sets the ExpireDate field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PremiumDomainsDownloadResponse) SetExpireDate(expireDate *time.Time) {
	p.ExpireDate = expireDate
	p.require(premiumDomainsDownloadResponseFieldExpireDate)
}

func (p *PremiumDomainsDownloadResponse) UnmarshalJSON(data []byte) error {
	type embed PremiumDomainsDownloadResponse
	var unmarshaler = struct {
		embed
		ExpireDate *internal.DateTime `json:"expireDate,omitempty"`
	}{
		embed: embed(*p),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*p = PremiumDomainsDownloadResponse(unmarshaler.embed)
	p.ExpireDate = unmarshaler.ExpireDate.TimePtr()
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PremiumDomainsDownloadResponse) MarshalJSON() ([]byte, error) {
	type embed PremiumDomainsDownloadResponse
	var marshaler = struct {
		embed
		ExpireDate *internal.DateTime `json:"expireDate,omitempty"`
	}{
		embed:      embed(*p),
		ExpireDate: internal.NewOptionalDateTime(p.ExpireDate),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (p *PremiumDomainsDownloadResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}
