// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	assert "github.com/stretchr/testify/assert"
	require "github.com/stretchr/testify/require"
	testing "testing"
)

func TestSettersTldPriceListRequest(t *testing.T) {
	t.Run("SetPerPage", func(t *testing.T) {
		obj := &TldPriceListRequest{}
		var fernTestValuePerPage *int
		obj.SetPerPage(fernTestValuePerPage)
		assert.Equal(t, fernTestValuePerPage, obj.PerPage)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPage", func(t *testing.T) {
		obj := &TldPriceListRequest{}
		var fernTestValuePage *int
		obj.SetPage(fernTestValuePage)
		assert.Equal(t, fernTestValuePage, obj.Page)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetDuration", func(t *testing.T) {
		obj := &TldPriceListRequest{}
		var fernTestValueDuration *int
		obj.SetDuration(fernTestValueDuration)
		assert.Equal(t, fernTestValueDuration, obj.Duration)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetTlds", func(t *testing.T) {
		obj := &TldPriceListRequest{}
		var fernTestValueTlds []*string
		obj.SetTlds(fernTestValueTlds)
		assert.Equal(t, fernTestValueTlds, obj.Tlds)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitTldPriceListRequest(t *testing.T) {
	t.Run("SetPerPage_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TldPriceListRequest{}
		var fernTestValuePerPage *int

		// Act
		obj.SetPerPage(fernTestValuePerPage)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPage_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TldPriceListRequest{}
		var fernTestValuePage *int

		// Act
		obj.SetPage(fernTestValuePage)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetDuration_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TldPriceListRequest{}
		var fernTestValueDuration *int

		// Act
		obj.SetDuration(fernTestValueDuration)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetTlds_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TldPriceListRequest{}
		var fernTestValueTlds []*string

		// Act
		obj.SetTlds(fernTestValueTlds)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersTldPriceListEntry(t *testing.T) {
	t.Run("SetTld", func(t *testing.T) {
		obj := &TldPriceListEntry{}
		var fernTestValueTld string
		obj.SetTld(fernTestValueTld)
		assert.Equal(t, fernTestValueTld, obj.Tld)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetDuration", func(t *testing.T) {
		obj := &TldPriceListEntry{}
		var fernTestValueDuration int
		obj.SetDuration(fernTestValueDuration)
		assert.Equal(t, fernTestValueDuration, obj.Duration)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetRegistrationPrice", func(t *testing.T) {
		obj := &TldPriceListEntry{}
		var fernTestValueRegistrationPrice *float64
		obj.SetRegistrationPrice(fernTestValueRegistrationPrice)
		assert.Equal(t, fernTestValueRegistrationPrice, obj.RegistrationPrice)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetRegistrationRetailPrice", func(t *testing.T) {
		obj := &TldPriceListEntry{}
		var fernTestValueRegistrationRetailPrice *float64
		obj.SetRegistrationRetailPrice(fernTestValueRegistrationRetailPrice)
		assert.Equal(t, fernTestValueRegistrationRetailPrice, obj.RegistrationRetailPrice)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetRegistrationOriginalPrice", func(t *testing.T) {
		obj := &TldPriceListEntry{}
		var fernTestValueRegistrationOriginalPrice *float64
		obj.SetRegistrationOriginalPrice(fernTestValueRegistrationOriginalPrice)
		assert.Equal(t, fernTestValueRegistrationOriginalPrice, obj.RegistrationOriginalPrice)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetRenewalPrice", func(t *testing.T) {
		obj := &TldPriceListEntry{}
		var fernTestValueRenewalPrice *float64
		obj.SetRenewalPrice(fernTestValueRenewalPrice)
		assert.Equal(t, fernTestValueRenewalPrice, obj.RenewalPrice)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetRenewalRetailPrice", func(t *testing.T) {
		obj := &TldPriceListEntry{}
		var fernTestValueRenewalRetailPrice *float64
		obj.SetRenewalRetailPrice(fernTestValueRenewalRetailPrice)
		assert.Equal(t, fernTestValueRenewalRetailPrice, obj.RenewalRetailPrice)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetRenewalOriginalPrice", func(t *testing.T) {
		obj := &TldPriceListEntry{}
		var fernTestValueRenewalOriginalPrice *float64
		obj.SetRenewalOriginalPrice(fernTestValueRenewalOriginalPrice)
		assert.Equal(t, fernTestValueRenewalOriginalPrice, obj.RenewalOriginalPrice)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetDomainRestorationPrice", func(t *testing.T) {
		obj := &TldPriceListEntry{}
		var fernTestValueDomainRestorationPrice *float64
		obj.SetDomainRestorationPrice(fernTestValueDomainRestorationPrice)
		assert.Equal(t, fernTestValueDomainRestorationPrice, obj.DomainRestorationPrice)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetDomainRestorationRetailPrice", func(t *testing.T) {
		obj := &TldPriceListEntry{}
		var fernTestValueDomainRestorationRetailPrice *float64
		obj.SetDomainRestorationRetailPrice(fernTestValueDomainRestorationRetailPrice)
		assert.Equal(t, fernTestValueDomainRestorationRetailPrice, obj.DomainRestorationRetailPrice)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetDomainRestorationOriginalPrice", func(t *testing.T) {
		obj := &TldPriceListEntry{}
		var fernTestValueDomainRestorationOriginalPrice *float64
		obj.SetDomainRestorationOriginalPrice(fernTestValueDomainRestorationOriginalPrice)
		assert.Equal(t, fernTestValueDomainRestorationOriginalPrice, obj.DomainRestorationOriginalPrice)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetTransferInPrice", func(t *testing.T) {
		obj := &TldPriceListEntry{}
		var fernTestValueTransferInPrice *float64
		obj.SetTransferInPrice(fernTestValueTransferInPrice)
		assert.Equal(t, fernTestValueTransferInPrice, obj.TransferInPrice)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetTransferInRetailPrice", func(t *testing.T) {
		obj := &TldPriceListEntry{}
		var fernTestValueTransferInRetailPrice *float64
		obj.SetTransferInRetailPrice(fernTestValueTransferInRetailPrice)
		assert.Equal(t, fernTestValueTransferInRetailPrice, obj.TransferInRetailPrice)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetTransferInOriginalPrice", func(t *testing.T) {
		obj := &TldPriceListEntry{}
		var fernTestValueTransferInOriginalPrice *float64
		obj.SetTransferInOriginalPrice(fernTestValueTransferInOriginalPrice)
		assert.Equal(t, fernTestValueTransferInOriginalPrice, obj.TransferInOriginalPrice)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersTldPriceListEntry(t *testing.T) {
	t.Run("GetTld", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TldPriceListEntry{}
		var expected string
		obj.Tld = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetTld(), "getter should return the property value")
	})

	t.Run("GetTld_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TldPriceListEntry
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetTld() // Should return zero value
	})

	t.Run("GetDuration", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TldPriceListEntry{}
		var expected int
		obj.Duration = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetDuration(), "getter should return the property value")
	})

	t.Run("GetDuration_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TldPriceListEntry
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetDuration() // Should return zero value
	})

	t.Run("GetRegistrationPrice", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TldPriceListEntry{}
		var expected *float64
		obj.RegistrationPrice = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetRegistrationPrice(), "getter should return the property value")
	})

	t.Run("GetRegistrationPrice_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TldPriceListEntry{}
		obj.RegistrationPrice = nil

		// Act & Assert
		assert.Nil(t, obj.GetRegistrationPrice(), "getter should return nil when property is nil")
	})

	t.Run("GetRegistrationPrice_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TldPriceListEntry
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetRegistrationPrice() // Should return zero value
	})

	t.Run("GetRegistrationRetailPrice", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TldPriceListEntry{}
		var expected *float64
		obj.RegistrationRetailPrice = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetRegistrationRetailPrice(), "getter should return the property value")
	})

	t.Run("GetRegistrationRetailPrice_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TldPriceListEntry{}
		obj.RegistrationRetailPrice = nil

		// Act & Assert
		assert.Nil(t, obj.GetRegistrationRetailPrice(), "getter should return nil when property is nil")
	})

	t.Run("GetRegistrationRetailPrice_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TldPriceListEntry
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetRegistrationRetailPrice() // Should return zero value
	})

	t.Run("GetRegistrationOriginalPrice", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TldPriceListEntry{}
		var expected *float64
		obj.RegistrationOriginalPrice = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetRegistrationOriginalPrice(), "getter should return the property value")
	})

	t.Run("GetRegistrationOriginalPrice_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TldPriceListEntry{}
		obj.RegistrationOriginalPrice = nil

		// Act & Assert
		assert.Nil(t, obj.GetRegistrationOriginalPrice(), "getter should return nil when property is nil")
	})

	t.Run("GetRegistrationOriginalPrice_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TldPriceListEntry
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetRegistrationOriginalPrice() // Should return zero value
	})

	t.Run("GetRenewalPrice", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TldPriceListEntry{}
		var expected *float64
		obj.RenewalPrice = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetRenewalPrice(), "getter should return the property value")
	})

	t.Run("GetRenewalPrice_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TldPriceListEntry{}
		obj.RenewalPrice = nil

		// Act & Assert
		assert.Nil(t, obj.GetRenewalPrice(), "getter should return nil when property is nil")
	})

	t.Run("GetRenewalPrice_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TldPriceListEntry
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetRenewalPrice() // Should return zero value
	})

	t.Run("GetRenewalRetailPrice", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TldPriceListEntry{}
		var expected *float64
		obj.RenewalRetailPrice = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetRenewalRetailPrice(), "getter should return the property value")
	})

	t.Run("GetRenewalRetailPrice_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TldPriceListEntry{}
		obj.RenewalRetailPrice = nil

		// Act & Assert
		assert.Nil(t, obj.GetRenewalRetailPrice(), "getter should return nil when property is nil")
	})

	t.Run("GetRenewalRetailPrice_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TldPriceListEntry
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetRenewalRetailPrice() // Should return zero value
	})

	t.Run("GetRenewalOriginalPrice", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TldPriceListEntry{}
		var expected *float64
		obj.RenewalOriginalPrice = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetRenewalOriginalPrice(), "getter should return the property value")
	})

	t.Run("GetRenewalOriginalPrice_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TldPriceListEntry{}
		obj.RenewalOriginalPrice = nil

		// Act & Assert
		assert.Nil(t, obj.GetRenewalOriginalPrice(), "getter should return nil when property is nil")
	})

	t.Run("GetRenewalOriginalPrice_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TldPriceListEntry
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetRenewalOriginalPrice() // Should return zero value
	})

	t.Run("GetDomainRestorationPrice", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TldPriceListEntry{}
		var expected *float64
		obj.DomainRestorationPrice = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetDomainRestorationPrice(), "getter should return the property value")
	})

	t.Run("GetDomainRestorationPrice_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TldPriceListEntry{}
		obj.DomainRestorationPrice = nil

		// Act & Assert
		assert.Nil(t, obj.GetDomainRestorationPrice(), "getter should return nil when property is nil")
	})

	t.Run("GetDomainRestorationPrice_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TldPriceListEntry
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetDomainRestorationPrice() // Should return zero value
	})

	t.Run("GetDomainRestorationRetailPrice", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TldPriceListEntry{}
		var expected *float64
		obj.DomainRestorationRetailPrice = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetDomainRestorationRetailPrice(), "getter should return the property value")
	})

	t.Run("GetDomainRestorationRetailPrice_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TldPriceListEntry{}
		obj.DomainRestorationRetailPrice = nil

		// Act & Assert
		assert.Nil(t, obj.GetDomainRestorationRetailPrice(), "getter should return nil when property is nil")
	})

	t.Run("GetDomainRestorationRetailPrice_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TldPriceListEntry
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetDomainRestorationRetailPrice() // Should return zero value
	})

	t.Run("GetDomainRestorationOriginalPrice", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TldPriceListEntry{}
		var expected *float64
		obj.DomainRestorationOriginalPrice = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetDomainRestorationOriginalPrice(), "getter should return the property value")
	})

	t.Run("GetDomainRestorationOriginalPrice_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TldPriceListEntry{}
		obj.DomainRestorationOriginalPrice = nil

		// Act & Assert
		assert.Nil(t, obj.GetDomainRestorationOriginalPrice(), "getter should return nil when property is nil")
	})

	t.Run("GetDomainRestorationOriginalPrice_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TldPriceListEntry
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetDomainRestorationOriginalPrice() // Should return zero value
	})

	t.Run("GetTransferInPrice", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TldPriceListEntry{}
		var expected *float64
		obj.TransferInPrice = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetTransferInPrice(), "getter should return the property value")
	})

	t.Run("GetTransferInPrice_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TldPriceListEntry{}
		obj.TransferInPrice = nil

		// Act & Assert
		assert.Nil(t, obj.GetTransferInPrice(), "getter should return nil when property is nil")
	})

	t.Run("GetTransferInPrice_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TldPriceListEntry
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetTransferInPrice() // Should return zero value
	})

	t.Run("GetTransferInRetailPrice", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TldPriceListEntry{}
		var expected *float64
		obj.TransferInRetailPrice = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetTransferInRetailPrice(), "getter should return the property value")
	})

	t.Run("GetTransferInRetailPrice_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TldPriceListEntry{}
		obj.TransferInRetailPrice = nil

		// Act & Assert
		assert.Nil(t, obj.GetTransferInRetailPrice(), "getter should return nil when property is nil")
	})

	t.Run("GetTransferInRetailPrice_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TldPriceListEntry
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetTransferInRetailPrice() // Should return zero value
	})

	t.Run("GetTransferInOriginalPrice", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TldPriceListEntry{}
		var expected *float64
		obj.TransferInOriginalPrice = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetTransferInOriginalPrice(), "getter should return the property value")
	})

	t.Run("GetTransferInOriginalPrice_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TldPriceListEntry{}
		obj.TransferInOriginalPrice = nil

		// Act & Assert
		assert.Nil(t, obj.GetTransferInOriginalPrice(), "getter should return nil when property is nil")
	})

	t.Run("GetTransferInOriginalPrice_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TldPriceListEntry
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetTransferInOriginalPrice() // Should return zero value
	})

}

func TestSettersMarkExplicitTldPriceListEntry(t *testing.T) {
	t.Run("SetTld_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TldPriceListEntry{}
		var fernTestValueTld string

		// Act
		obj.SetTld(fernTestValueTld)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetDuration_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TldPriceListEntry{}
		var fernTestValueDuration int

		// Act
		obj.SetDuration(fernTestValueDuration)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetRegistrationPrice_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TldPriceListEntry{}
		var fernTestValueRegistrationPrice *float64

		// Act
		obj.SetRegistrationPrice(fernTestValueRegistrationPrice)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetRegistrationRetailPrice_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TldPriceListEntry{}
		var fernTestValueRegistrationRetailPrice *float64

		// Act
		obj.SetRegistrationRetailPrice(fernTestValueRegistrationRetailPrice)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetRegistrationOriginalPrice_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TldPriceListEntry{}
		var fernTestValueRegistrationOriginalPrice *float64

		// Act
		obj.SetRegistrationOriginalPrice(fernTestValueRegistrationOriginalPrice)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetRenewalPrice_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TldPriceListEntry{}
		var fernTestValueRenewalPrice *float64

		// Act
		obj.SetRenewalPrice(fernTestValueRenewalPrice)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetRenewalRetailPrice_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TldPriceListEntry{}
		var fernTestValueRenewalRetailPrice *float64

		// Act
		obj.SetRenewalRetailPrice(fernTestValueRenewalRetailPrice)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetRenewalOriginalPrice_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TldPriceListEntry{}
		var fernTestValueRenewalOriginalPrice *float64

		// Act
		obj.SetRenewalOriginalPrice(fernTestValueRenewalOriginalPrice)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetDomainRestorationPrice_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TldPriceListEntry{}
		var fernTestValueDomainRestorationPrice *float64

		// Act
		obj.SetDomainRestorationPrice(fernTestValueDomainRestorationPrice)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetDomainRestorationRetailPrice_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TldPriceListEntry{}
		var fernTestValueDomainRestorationRetailPrice *float64

		// Act
		obj.SetDomainRestorationRetailPrice(fernTestValueDomainRestorationRetailPrice)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetDomainRestorationOriginalPrice_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TldPriceListEntry{}
		var fernTestValueDomainRestorationOriginalPrice *float64

		// Act
		obj.SetDomainRestorationOriginalPrice(fernTestValueDomainRestorationOriginalPrice)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetTransferInPrice_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TldPriceListEntry{}
		var fernTestValueTransferInPrice *float64

		// Act
		obj.SetTransferInPrice(fernTestValueTransferInPrice)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetTransferInRetailPrice_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TldPriceListEntry{}
		var fernTestValueTransferInRetailPrice *float64

		// Act
		obj.SetTransferInRetailPrice(fernTestValueTransferInRetailPrice)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetTransferInOriginalPrice_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TldPriceListEntry{}
		var fernTestValueTransferInOriginalPrice *float64

		// Act
		obj.SetTransferInOriginalPrice(fernTestValueTransferInOriginalPrice)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersTldPriceListResponse(t *testing.T) {
	t.Run("SetLastPage", func(t *testing.T) {
		obj := &TldPriceListResponse{}
		var fernTestValueLastPage int
		obj.SetLastPage(fernTestValueLastPage)
		assert.Equal(t, fernTestValueLastPage, obj.LastPage)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetNextPage", func(t *testing.T) {
		obj := &TldPriceListResponse{}
		var fernTestValueNextPage *int
		obj.SetNextPage(fernTestValueNextPage)
		assert.Equal(t, fernTestValueNextPage, obj.NextPage)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetTotalCount", func(t *testing.T) {
		obj := &TldPriceListResponse{}
		var fernTestValueTotalCount int
		obj.SetTotalCount(fernTestValueTotalCount)
		assert.Equal(t, fernTestValueTotalCount, obj.TotalCount)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetFrom", func(t *testing.T) {
		obj := &TldPriceListResponse{}
		var fernTestValueFrom int
		obj.SetFrom(fernTestValueFrom)
		assert.Equal(t, fernTestValueFrom, obj.From)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetTo", func(t *testing.T) {
		obj := &TldPriceListResponse{}
		var fernTestValueTo int
		obj.SetTo(fernTestValueTo)
		assert.Equal(t, fernTestValueTo, obj.To)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPricing", func(t *testing.T) {
		obj := &TldPriceListResponse{}
		var fernTestValuePricing []*TldPriceListEntry
		obj.SetPricing(fernTestValuePricing)
		assert.Equal(t, fernTestValuePricing, obj.Pricing)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersTldPriceListResponse(t *testing.T) {
	t.Run("GetLastPage", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TldPriceListResponse{}
		var expected int
		obj.LastPage = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetLastPage(), "getter should return the property value")
	})

	t.Run("GetLastPage_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TldPriceListResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetLastPage() // Should return zero value
	})

	t.Run("GetNextPage", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TldPriceListResponse{}
		var expected *int
		obj.NextPage = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetNextPage(), "getter should return the property value")
	})

	t.Run("GetNextPage_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TldPriceListResponse{}
		obj.NextPage = nil

		// Act & Assert
		assert.Nil(t, obj.GetNextPage(), "getter should return nil when property is nil")
	})

	t.Run("GetNextPage_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TldPriceListResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetNextPage() // Should return zero value
	})

	t.Run("GetTotalCount", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TldPriceListResponse{}
		var expected int
		obj.TotalCount = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetTotalCount(), "getter should return the property value")
	})

	t.Run("GetTotalCount_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TldPriceListResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetTotalCount() // Should return zero value
	})

	t.Run("GetFrom", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TldPriceListResponse{}
		var expected int
		obj.From = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetFrom(), "getter should return the property value")
	})

	t.Run("GetFrom_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TldPriceListResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetFrom() // Should return zero value
	})

	t.Run("GetTo", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TldPriceListResponse{}
		var expected int
		obj.To = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetTo(), "getter should return the property value")
	})

	t.Run("GetTo_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TldPriceListResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetTo() // Should return zero value
	})

	t.Run("GetPricing", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TldPriceListResponse{}
		var expected []*TldPriceListEntry
		obj.Pricing = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetPricing(), "getter should return the property value")
	})

	t.Run("GetPricing_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TldPriceListResponse{}
		obj.Pricing = nil

		// Act & Assert
		assert.Nil(t, obj.GetPricing(), "getter should return nil when property is nil")
	})

	t.Run("GetPricing_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TldPriceListResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetPricing() // Should return zero value
	})

}

func TestSettersMarkExplicitTldPriceListResponse(t *testing.T) {
	t.Run("SetLastPage_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TldPriceListResponse{}
		var fernTestValueLastPage int

		// Act
		obj.SetLastPage(fernTestValueLastPage)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetNextPage_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TldPriceListResponse{}
		var fernTestValueNextPage *int

		// Act
		obj.SetNextPage(fernTestValueNextPage)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetTotalCount_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TldPriceListResponse{}
		var fernTestValueTotalCount int

		// Act
		obj.SetTotalCount(fernTestValueTotalCount)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetFrom_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TldPriceListResponse{}
		var fernTestValueFrom int

		// Act
		obj.SetFrom(fernTestValueFrom)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetTo_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TldPriceListResponse{}
		var fernTestValueTo int

		// Act
		obj.SetTo(fernTestValueTo)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPricing_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TldPriceListResponse{}
		var fernTestValuePricing []*TldPriceListEntry

		// Act
		obj.SetPricing(fernTestValuePricing)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestJSONMarshalingTldPriceListEntry(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TldPriceListEntry{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled TldPriceListEntry
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj TldPriceListEntry
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj TldPriceListEntry
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingTldPriceListResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TldPriceListResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled TldPriceListResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj TldPriceListResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj TldPriceListResponse
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestStringTldPriceListEntry(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &TldPriceListEntry{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TldPriceListEntry
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringTldPriceListResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &TldPriceListResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TldPriceListResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestExtraPropertiesTldPriceListEntry(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &TldPriceListEntry{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TldPriceListEntry
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesTldPriceListResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &TldPriceListResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TldPriceListResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}
