// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/namedotcom/core-api-go/internal"
	big "math/big"
)

var (
	cancelOutboundTransferRequestFieldDomainName = big.NewInt(1 << 0)
)

type CancelOutboundTransferRequest struct {
	// DomainName is the domain whose transfer out should be canceled.
	DomainName string       `json:"-" url:"-"`
	Body       *EmptyObject `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CancelOutboundTransferRequest) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetDomainName sets the DomainName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CancelOutboundTransferRequest) SetDomainName(domainName string) {
	c.DomainName = domainName
	c.require(cancelOutboundTransferRequestFieldDomainName)
}

func (c *CancelOutboundTransferRequest) UnmarshalJSON(data []byte) error {
	body := new(EmptyObject)
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	c.Body = body
	return nil
}

func (c *CancelOutboundTransferRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(c.Body)
}

var (
	cancelTransferRequestFieldDomainName = big.NewInt(1 << 0)
)

type CancelTransferRequest struct {
	// DomainName is the domain to cancel the transfer for.
	DomainName string       `json:"-" url:"-"`
	Body       *EmptyObject `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CancelTransferRequest) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetDomainName sets the DomainName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CancelTransferRequest) SetDomainName(domainName string) {
	c.DomainName = domainName
	c.require(cancelTransferRequestFieldDomainName)
}

func (c *CancelTransferRequest) UnmarshalJSON(data []byte) error {
	body := new(EmptyObject)
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	c.Body = body
	return nil
}

func (c *CancelTransferRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(c.Body)
}

var (
	createInternalTransferInRequestFieldDomainName = big.NewInt(1 << 0)
	createInternalTransferInRequestFieldAuthCode   = big.NewInt(1 << 1)
	createInternalTransferInRequestFieldContacts   = big.NewInt(1 << 2)
)

type CreateInternalTransferInRequest struct {
	// Fully qualified domain name to transfer in. The domain must be registered in another name.com account (the losing account).
	DomainName string `json:"domainName" url:"-"`
	// Transfer authorization code (EPP/auth code) for the domain. The losing account holder must obtain this code from the [name.com](https://www.name.com) dashboard; it is not exposed by this API for the losing account.
	AuthCode string `json:"authCode" url:"-"`
	// WHOIS contacts to apply after the transfer. If omitted, the gaining account's default contacts are applied. If provided, include any roles to override; omitted roles use the gaining account's default contacts. Each supplied role must include complete contact fields. A registrar contact-change transfer lock may apply according to the gaining account's settings, consistent with the Set Contacts endpoint.
	Contacts *ContactsRequest `json:"contacts,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CreateInternalTransferInRequest) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetDomainName sets the DomainName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateInternalTransferInRequest) SetDomainName(domainName string) {
	c.DomainName = domainName
	c.require(createInternalTransferInRequestFieldDomainName)
}

// SetAuthCode sets the AuthCode field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateInternalTransferInRequest) SetAuthCode(authCode string) {
	c.AuthCode = authCode
	c.require(createInternalTransferInRequestFieldAuthCode)
}

// SetContacts sets the Contacts field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateInternalTransferInRequest) SetContacts(contacts *ContactsRequest) {
	c.Contacts = contacts
	c.require(createInternalTransferInRequestFieldContacts)
}

func (c *CreateInternalTransferInRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateInternalTransferInRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*c = CreateInternalTransferInRequest(body)
	return nil
}

func (c *CreateInternalTransferInRequest) MarshalJSON() ([]byte, error) {
	type embed CreateInternalTransferInRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	createTransferRequestFieldAuthCode       = big.NewInt(1 << 0)
	createTransferRequestFieldDomainName     = big.NewInt(1 << 1)
	createTransferRequestFieldPrivacyEnabled = big.NewInt(1 << 2)
	createTransferRequestFieldPurchasePrice  = big.NewInt(1 << 3)
)

type CreateTransferRequest struct {
	// AuthCode is the authorization code for the transfer. Not all TLDs require authorization codes, but most do.
	AuthCode string `json:"authCode" url:"-"`
	// DomainName is the domain you want to transfer to name.com.
	DomainName string `json:"domainName" url:"-"`
	// PrivacyEnabled is a flag on whether to purchase Whois Privacy with the transfer. If this flag is omitted from the request, the system will check the account's Whois Privacy auto-add settings. If auto-add is enabled in your account settings, Whois Privacy will be added by default, provided the TLD supports it.
	PrivacyEnabled *bool `json:"privacyEnabled,omitempty" url:"-"`
	// PurchasePrice is the USD inbound transfer fee, before VAT. VAT is applied when applicable and must not be included here. If sent, must match Get Pricing `transferPrice` exactly or the request will fail.. **Omit** for standard (non-premium) transfers. **Required** for premium transfers — use `transferPrice` from [Get Pricing](/api/v1/reference/domains/get-pricing-for-domain).
	PurchasePrice *float64 `json:"purchasePrice,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CreateTransferRequest) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetAuthCode sets the AuthCode field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateTransferRequest) SetAuthCode(authCode string) {
	c.AuthCode = authCode
	c.require(createTransferRequestFieldAuthCode)
}

// SetDomainName sets the DomainName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateTransferRequest) SetDomainName(domainName string) {
	c.DomainName = domainName
	c.require(createTransferRequestFieldDomainName)
}

// SetPrivacyEnabled sets the PrivacyEnabled field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateTransferRequest) SetPrivacyEnabled(privacyEnabled *bool) {
	c.PrivacyEnabled = privacyEnabled
	c.require(createTransferRequestFieldPrivacyEnabled)
}

// SetPurchasePrice sets the PurchasePrice field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateTransferRequest) SetPurchasePrice(purchasePrice *float64) {
	c.PurchasePrice = purchasePrice
	c.require(createTransferRequestFieldPurchasePrice)
}

func (c *CreateTransferRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateTransferRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*c = CreateTransferRequest(body)
	return nil
}

func (c *CreateTransferRequest) MarshalJSON() ([]byte, error) {
	type embed CreateTransferRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	getTransferRequestFieldDomainName = big.NewInt(1 << 0)
)

type GetTransferRequest struct {
	// DomainName is the domain you want to get the transfer information for.
	DomainName string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetTransferRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetDomainName sets the DomainName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetTransferRequest) SetDomainName(domainName string) {
	g.DomainName = domainName
	g.require(getTransferRequestFieldDomainName)
}

var (
	getTransferEligibilityRequestFieldDomainName = big.NewInt(1 << 0)
)

type GetTransferEligibilityRequest struct {
	// The domain to check transfer eligibility for. Punycode is normalized server-side, so either ASCII or UTF-8 is accepted.
	DomainName string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetTransferEligibilityRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetDomainName sets the DomainName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetTransferEligibilityRequest) SetDomainName(domainName string) {
	g.DomainName = domainName
	g.require(getTransferEligibilityRequestFieldDomainName)
}

var (
	listTransfersRequestFieldPerPage = big.NewInt(1 << 0)
	listTransfersRequestFieldPage    = big.NewInt(1 << 1)
)

type ListTransfersRequest struct {
	// Per Page is the number of records to return per request. Per Page defaults to 500.
	PerPage *int `json:"-" url:"perPage,omitempty"`
	// Page is which page to return.
	Page *int `json:"-" url:"page,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListTransfersRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetPerPage sets the PerPage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListTransfersRequest) SetPerPage(perPage *int) {
	l.PerPage = perPage
	l.require(listTransfersRequestFieldPerPage)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListTransfersRequest) SetPage(page *int) {
	l.Page = page
	l.require(listTransfersRequestFieldPage)
}

// Response after successfully canceling a domain transfer out request.
var (
	cancelTransferOutResponseFieldDomainName = big.NewInt(1 << 0)
	cancelTransferOutResponseFieldStatus     = big.NewInt(1 << 1)
)

type CancelTransferOutResponse struct {
	// The punycode-encoded domain name.
	DomainName string `json:"domainName" url:"domainName"`
	// The transfer-out status after the operation (e.g. canceled when the cancel succeeded).
	Status CancelTransferOutResponseStatus `json:"status" url:"status"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CancelTransferOutResponse) GetDomainName() string {
	if c == nil {
		return ""
	}
	return c.DomainName
}

func (c *CancelTransferOutResponse) GetStatus() CancelTransferOutResponseStatus {
	if c == nil {
		return ""
	}
	return c.Status
}

func (c *CancelTransferOutResponse) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CancelTransferOutResponse) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetDomainName sets the DomainName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CancelTransferOutResponse) SetDomainName(domainName string) {
	c.DomainName = domainName
	c.require(cancelTransferOutResponseFieldDomainName)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CancelTransferOutResponse) SetStatus(status CancelTransferOutResponseStatus) {
	c.Status = status
	c.require(cancelTransferOutResponseFieldStatus)
}

func (c *CancelTransferOutResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler CancelTransferOutResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CancelTransferOutResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CancelTransferOutResponse) MarshalJSON() ([]byte, error) {
	type embed CancelTransferOutResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CancelTransferOutResponse) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

// The transfer-out status after the operation (e.g. canceled when the cancel succeeded).
type CancelTransferOutResponseStatus string

const (
	CancelTransferOutResponseStatusCanceled CancelTransferOutResponseStatus = "canceled"
)

func NewCancelTransferOutResponseStatusFromString(s string) (CancelTransferOutResponseStatus, error) {
	switch s {
	case "canceled":
		return CancelTransferOutResponseStatusCanceled, nil
	}
	var t CancelTransferOutResponseStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CancelTransferOutResponseStatus) Ptr() *CancelTransferOutResponseStatus {
	return &c
}

// CreateTransferResponse returns the newly created transfer resource as well as the order information.
var (
	createTransferResponseFieldOrder     = big.NewInt(1 << 0)
	createTransferResponseFieldTotalPaid = big.NewInt(1 << 1)
	createTransferResponseFieldTransfer  = big.NewInt(1 << 2)
	createTransferResponseFieldWarnings  = big.NewInt(1 << 3)
)

type CreateTransferResponse struct {
	// Order is an identifier for this purchase.
	Order int `json:"order" url:"order"`
	// TotalPaid is the total amount paid, including VAT and Whois Privacy.
	TotalPaid float64   `json:"totalPaid" url:"totalPaid"`
	Transfer  *Transfer `json:"transfer" url:"transfer"`
	// Optional transfer warnings surfaced by the API when non-blocking registry statuses are detected.
	Warnings *CreateTransferResponseWarnings `json:"warnings,omitempty" url:"warnings,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CreateTransferResponse) GetOrder() int {
	if c == nil {
		return 0
	}
	return c.Order
}

func (c *CreateTransferResponse) GetTotalPaid() float64 {
	if c == nil {
		return 0
	}
	return c.TotalPaid
}

func (c *CreateTransferResponse) GetTransfer() *Transfer {
	if c == nil {
		return nil
	}
	return c.Transfer
}

func (c *CreateTransferResponse) GetWarnings() *CreateTransferResponseWarnings {
	if c == nil {
		return nil
	}
	return c.Warnings
}

func (c *CreateTransferResponse) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CreateTransferResponse) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetOrder sets the Order field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateTransferResponse) SetOrder(order int) {
	c.Order = order
	c.require(createTransferResponseFieldOrder)
}

// SetTotalPaid sets the TotalPaid field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateTransferResponse) SetTotalPaid(totalPaid float64) {
	c.TotalPaid = totalPaid
	c.require(createTransferResponseFieldTotalPaid)
}

// SetTransfer sets the Transfer field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateTransferResponse) SetTransfer(transfer *Transfer) {
	c.Transfer = transfer
	c.require(createTransferResponseFieldTransfer)
}

// SetWarnings sets the Warnings field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateTransferResponse) SetWarnings(warnings *CreateTransferResponseWarnings) {
	c.Warnings = warnings
	c.require(createTransferResponseFieldWarnings)
}

func (c *CreateTransferResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateTransferResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreateTransferResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreateTransferResponse) MarshalJSON() ([]byte, error) {
	type embed CreateTransferResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CreateTransferResponse) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

// Optional transfer warnings surfaced by the API when non-blocking registry statuses are detected.
var (
	createTransferResponseWarningsFieldMessage  = big.NewInt(1 << 0)
	createTransferResponseWarningsFieldStatuses = big.NewInt(1 << 1)
)

type CreateTransferResponseWarnings struct {
	// Brief guidance for resolving potential transfer issues.
	Message *string `json:"message,omitempty" url:"message,omitempty"`
	// Registry status values that triggered the warning.
	Statuses []string `json:"statuses,omitempty" url:"statuses,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CreateTransferResponseWarnings) GetMessage() *string {
	if c == nil {
		return nil
	}
	return c.Message
}

func (c *CreateTransferResponseWarnings) GetStatuses() []string {
	if c == nil {
		return nil
	}
	return c.Statuses
}

func (c *CreateTransferResponseWarnings) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CreateTransferResponseWarnings) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateTransferResponseWarnings) SetMessage(message *string) {
	c.Message = message
	c.require(createTransferResponseWarningsFieldMessage)
}

// SetStatuses sets the Statuses field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateTransferResponseWarnings) SetStatuses(statuses []string) {
	c.Statuses = statuses
	c.require(createTransferResponseWarningsFieldStatuses)
}

func (c *CreateTransferResponseWarnings) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateTransferResponseWarnings
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreateTransferResponseWarnings(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreateTransferResponseWarnings) MarshalJSON() ([]byte, error) {
	type embed CreateTransferResponseWarnings
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CreateTransferResponseWarnings) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

// ListTransfersResponse returns the list of pending transfers as well as the pagination information if relevant.
var (
	listTransfersResponseFieldLastPage   = big.NewInt(1 << 0)
	listTransfersResponseFieldNextPage   = big.NewInt(1 << 1)
	listTransfersResponseFieldTotalCount = big.NewInt(1 << 2)
	listTransfersResponseFieldFrom       = big.NewInt(1 << 3)
	listTransfersResponseFieldTo         = big.NewInt(1 << 4)
	listTransfersResponseFieldTransfers  = big.NewInt(1 << 5)
)

type ListTransfersResponse struct {
	// LastPage is the identifier for the final page of results. It is only populated if there is another page of results after the current page.
	LastPage *int `json:"lastPage,omitempty" url:"lastPage,omitempty"`
	// NextPage is the identifier for the next page of results. It is only populated if there is another page of results after the current page.
	NextPage *int `json:"nextPage,omitempty" url:"nextPage,omitempty"`
	// TotalCount is total number of results.
	TotalCount int `json:"totalCount" url:"totalCount"`
	// From specifies starting record number on current page.
	From int `json:"from" url:"from"`
	// To specifies ending record number on current page.
	To int `json:"to" url:"to"`
	// Transfers is a list of pending transfers
	Transfers []*Transfer `json:"transfers" url:"transfers"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *ListTransfersResponse) GetLastPage() *int {
	if l == nil {
		return nil
	}
	return l.LastPage
}

func (l *ListTransfersResponse) GetNextPage() *int {
	if l == nil {
		return nil
	}
	return l.NextPage
}

func (l *ListTransfersResponse) GetTotalCount() int {
	if l == nil {
		return 0
	}
	return l.TotalCount
}

func (l *ListTransfersResponse) GetFrom() int {
	if l == nil {
		return 0
	}
	return l.From
}

func (l *ListTransfersResponse) GetTo() int {
	if l == nil {
		return 0
	}
	return l.To
}

func (l *ListTransfersResponse) GetTransfers() []*Transfer {
	if l == nil {
		return nil
	}
	return l.Transfers
}

func (l *ListTransfersResponse) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *ListTransfersResponse) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetLastPage sets the LastPage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListTransfersResponse) SetLastPage(lastPage *int) {
	l.LastPage = lastPage
	l.require(listTransfersResponseFieldLastPage)
}

// SetNextPage sets the NextPage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListTransfersResponse) SetNextPage(nextPage *int) {
	l.NextPage = nextPage
	l.require(listTransfersResponseFieldNextPage)
}

// SetTotalCount sets the TotalCount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListTransfersResponse) SetTotalCount(totalCount int) {
	l.TotalCount = totalCount
	l.require(listTransfersResponseFieldTotalCount)
}

// SetFrom sets the From field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListTransfersResponse) SetFrom(from int) {
	l.From = from
	l.require(listTransfersResponseFieldFrom)
}

// SetTo sets the To field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListTransfersResponse) SetTo(to int) {
	l.To = to
	l.require(listTransfersResponseFieldTo)
}

// SetTransfers sets the Transfers field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListTransfersResponse) SetTransfers(transfers []*Transfer) {
	l.Transfers = transfers
	l.require(listTransfersResponseFieldTransfers)
}

func (l *ListTransfersResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ListTransfersResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = ListTransfersResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *ListTransfersResponse) MarshalJSON() ([]byte, error) {
	type embed ListTransfersResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *ListTransfersResponse) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}

// Transfer contains all relevant data for a domain transfer to name.com.
var (
	transferFieldDomainName = big.NewInt(1 << 0)
	transferFieldEmail      = big.NewInt(1 << 1)
	transferFieldStatus     = big.NewInt(1 << 2)
)

type Transfer struct {
	// DomainName is the domain to be transfered to name.com.
	DomainName string `json:"domainName" url:"domainName"`
	// Email is the email address that the approval email was sent to. Not every TLD requries an approval email. This is usually pulled from Whois.
	Email  *string        `json:"email,omitempty" url:"email,omitempty"`
	Status TransferStatus `json:"status" url:"status"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (t *Transfer) GetDomainName() string {
	if t == nil {
		return ""
	}
	return t.DomainName
}

func (t *Transfer) GetEmail() *string {
	if t == nil {
		return nil
	}
	return t.Email
}

func (t *Transfer) GetStatus() TransferStatus {
	if t == nil {
		return ""
	}
	return t.Status
}

func (t *Transfer) GetExtraProperties() map[string]interface{} {
	if t == nil {
		return nil
	}
	return t.extraProperties
}

func (t *Transfer) require(field *big.Int) {
	if t.explicitFields == nil {
		t.explicitFields = big.NewInt(0)
	}
	t.explicitFields.Or(t.explicitFields, field)
}

// SetDomainName sets the DomainName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *Transfer) SetDomainName(domainName string) {
	t.DomainName = domainName
	t.require(transferFieldDomainName)
}

// SetEmail sets the Email field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *Transfer) SetEmail(email *string) {
	t.Email = email
	t.require(transferFieldEmail)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *Transfer) SetStatus(status TransferStatus) {
	t.Status = status
	t.require(transferFieldStatus)
}

func (t *Transfer) UnmarshalJSON(data []byte) error {
	type unmarshaler Transfer
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*t = Transfer(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *t)
	if err != nil {
		return err
	}
	t.extraProperties = extraProperties
	t.rawJSON = json.RawMessage(data)
	return nil
}

func (t *Transfer) MarshalJSON() ([]byte, error) {
	type embed Transfer
	var marshaler = struct {
		embed
	}{
		embed: embed(*t),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, t.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (t *Transfer) String() string {
	if t == nil {
		return "<nil>"
	}
	if len(t.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(t.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(t); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", t)
}

// Result of a transfer eligibility check. Indicates whether the domain is currently registered at name.com (in any account) and whether the TLD supports internal transfer between name.com accounts.
var (
	transferEligibilityResponseFieldDomainName               = big.NewInt(1 << 0)
	transferEligibilityResponseFieldAtName                   = big.NewInt(1 << 1)
	transferEligibilityResponseFieldSupportsInternalTransfer = big.NewInt(1 << 2)
)

type TransferEligibilityResponse struct {
	// The domain that was checked, in its canonical (ASCII / punycode) form.
	DomainName string `json:"domainName" url:"domainName"`
	// Whether the domain is currently registered at name.com (in any account).
	AtName bool `json:"atName" url:"atName"`
	// Whether the TLD supports internal transfer between name.com accounts. Mirrors the TLD-level flag returned by Get Tld Requirements. Does not reflect per-account allowlist eligibility for the internal transfer-in API.
	SupportsInternalTransfer bool `json:"supportsInternalTransfer" url:"supportsInternalTransfer"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (t *TransferEligibilityResponse) GetDomainName() string {
	if t == nil {
		return ""
	}
	return t.DomainName
}

func (t *TransferEligibilityResponse) GetAtName() bool {
	if t == nil {
		return false
	}
	return t.AtName
}

func (t *TransferEligibilityResponse) GetSupportsInternalTransfer() bool {
	if t == nil {
		return false
	}
	return t.SupportsInternalTransfer
}

func (t *TransferEligibilityResponse) GetExtraProperties() map[string]interface{} {
	if t == nil {
		return nil
	}
	return t.extraProperties
}

func (t *TransferEligibilityResponse) require(field *big.Int) {
	if t.explicitFields == nil {
		t.explicitFields = big.NewInt(0)
	}
	t.explicitFields.Or(t.explicitFields, field)
}

// SetDomainName sets the DomainName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TransferEligibilityResponse) SetDomainName(domainName string) {
	t.DomainName = domainName
	t.require(transferEligibilityResponseFieldDomainName)
}

// SetAtName sets the AtName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TransferEligibilityResponse) SetAtName(atName bool) {
	t.AtName = atName
	t.require(transferEligibilityResponseFieldAtName)
}

// SetSupportsInternalTransfer sets the SupportsInternalTransfer field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TransferEligibilityResponse) SetSupportsInternalTransfer(supportsInternalTransfer bool) {
	t.SupportsInternalTransfer = supportsInternalTransfer
	t.require(transferEligibilityResponseFieldSupportsInternalTransfer)
}

func (t *TransferEligibilityResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler TransferEligibilityResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*t = TransferEligibilityResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *t)
	if err != nil {
		return err
	}
	t.extraProperties = extraProperties
	t.rawJSON = json.RawMessage(data)
	return nil
}

func (t *TransferEligibilityResponse) MarshalJSON() ([]byte, error) {
	type embed TransferEligibilityResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*t),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, t.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (t *TransferEligibilityResponse) String() string {
	if t == nil {
		return "<nil>"
	}
	if len(t.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(t.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(t); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", t)
}

// Terminal (finished; will not change):
// - **completed**: Completed.
// - **failed**: Failed.
// - **canceled**: Canceled by the user.
// - **canceled_pending_refund**: Canceled; refund processing.
//
// Non-terminal (in progress; may change):
// - **pending**: Requested.
// - **submitting_transfer**: Being submitted to the registry.
// - **pending_new_auth_code**: New auth code required.
// - **pending_unlock**: Waiting for losing registrar unlock.
// - **pending_registry_unlock**: Waiting for registry unlock.
// - **pending_transfer**: Pending at the registry.
// - **pending_insert**: Transfer complete; domain will be added to the account.
// - **rejected**: Rejected at the losing registrar.
type TransferStatus string

const (
	TransferStatusCanceled              TransferStatus = "canceled"
	TransferStatusCanceledPendingRefund TransferStatus = "canceled_pending_refund"
	TransferStatusCompleted             TransferStatus = "completed"
	TransferStatusFailed                TransferStatus = "failed"
	TransferStatusPending               TransferStatus = "pending"
	TransferStatusPendingInsert         TransferStatus = "pending_insert"
	TransferStatusPendingNewAuthCode    TransferStatus = "pending_new_auth_code"
	TransferStatusPendingRegistryUnlock TransferStatus = "pending_registry_unlock"
	TransferStatusPendingTransfer       TransferStatus = "pending_transfer"
	TransferStatusPendingUnlock         TransferStatus = "pending_unlock"
	TransferStatusRejected              TransferStatus = "rejected"
	TransferStatusSubmittingTransfer    TransferStatus = "submitting_transfer"
)

func NewTransferStatusFromString(s string) (TransferStatus, error) {
	switch s {
	case "canceled":
		return TransferStatusCanceled, nil
	case "canceled_pending_refund":
		return TransferStatusCanceledPendingRefund, nil
	case "completed":
		return TransferStatusCompleted, nil
	case "failed":
		return TransferStatusFailed, nil
	case "pending":
		return TransferStatusPending, nil
	case "pending_insert":
		return TransferStatusPendingInsert, nil
	case "pending_new_auth_code":
		return TransferStatusPendingNewAuthCode, nil
	case "pending_registry_unlock":
		return TransferStatusPendingRegistryUnlock, nil
	case "pending_transfer":
		return TransferStatusPendingTransfer, nil
	case "pending_unlock":
		return TransferStatusPendingUnlock, nil
	case "rejected":
		return TransferStatusRejected, nil
	case "submitting_transfer":
		return TransferStatusSubmittingTransfer, nil
	}
	var t TransferStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (t TransferStatus) Ptr() *TransferStatus {
	return &t
}
