// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	assert "github.com/stretchr/testify/assert"
	require "github.com/stretchr/testify/require"
	testing "testing"
)

func TestSettersCreateVanityNameserverBody(t *testing.T) {
	t.Run("SetDomainName", func(t *testing.T) {
		obj := &CreateVanityNameserverBody{}
		var fernTestValueDomainName string
		obj.SetDomainName(fernTestValueDomainName)
		assert.Equal(t, fernTestValueDomainName, obj.DomainName)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetHostname", func(t *testing.T) {
		obj := &CreateVanityNameserverBody{}
		var fernTestValueHostname string
		obj.SetHostname(fernTestValueHostname)
		assert.Equal(t, fernTestValueHostname, obj.Hostname)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetIps", func(t *testing.T) {
		obj := &CreateVanityNameserverBody{}
		var fernTestValueIps []string
		obj.SetIps(fernTestValueIps)
		assert.Equal(t, fernTestValueIps, obj.Ips)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitCreateVanityNameserverBody(t *testing.T) {
	t.Run("SetDomainName_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateVanityNameserverBody{}
		var fernTestValueDomainName string

		// Act
		obj.SetDomainName(fernTestValueDomainName)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetHostname_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateVanityNameserverBody{}
		var fernTestValueHostname string

		// Act
		obj.SetHostname(fernTestValueHostname)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetIps_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateVanityNameserverBody{}
		var fernTestValueIps []string

		// Act
		obj.SetIps(fernTestValueIps)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersDeleteVanityNameserverRequest(t *testing.T) {
	t.Run("SetDomainName", func(t *testing.T) {
		obj := &DeleteVanityNameserverRequest{}
		var fernTestValueDomainName string
		obj.SetDomainName(fernTestValueDomainName)
		assert.Equal(t, fernTestValueDomainName, obj.DomainName)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetHostname", func(t *testing.T) {
		obj := &DeleteVanityNameserverRequest{}
		var fernTestValueHostname string
		obj.SetHostname(fernTestValueHostname)
		assert.Equal(t, fernTestValueHostname, obj.Hostname)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitDeleteVanityNameserverRequest(t *testing.T) {
	t.Run("SetDomainName_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DeleteVanityNameserverRequest{}
		var fernTestValueDomainName string

		// Act
		obj.SetDomainName(fernTestValueDomainName)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetHostname_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DeleteVanityNameserverRequest{}
		var fernTestValueHostname string

		// Act
		obj.SetHostname(fernTestValueHostname)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersGetVanityNameserverRequest(t *testing.T) {
	t.Run("SetDomainName", func(t *testing.T) {
		obj := &GetVanityNameserverRequest{}
		var fernTestValueDomainName string
		obj.SetDomainName(fernTestValueDomainName)
		assert.Equal(t, fernTestValueDomainName, obj.DomainName)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetHostname", func(t *testing.T) {
		obj := &GetVanityNameserverRequest{}
		var fernTestValueHostname string
		obj.SetHostname(fernTestValueHostname)
		assert.Equal(t, fernTestValueHostname, obj.Hostname)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitGetVanityNameserverRequest(t *testing.T) {
	t.Run("SetDomainName_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetVanityNameserverRequest{}
		var fernTestValueDomainName string

		// Act
		obj.SetDomainName(fernTestValueDomainName)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetHostname_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetVanityNameserverRequest{}
		var fernTestValueHostname string

		// Act
		obj.SetHostname(fernTestValueHostname)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersListVanityNameserversRequest(t *testing.T) {
	t.Run("SetDomainName", func(t *testing.T) {
		obj := &ListVanityNameserversRequest{}
		var fernTestValueDomainName string
		obj.SetDomainName(fernTestValueDomainName)
		assert.Equal(t, fernTestValueDomainName, obj.DomainName)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPerPage", func(t *testing.T) {
		obj := &ListVanityNameserversRequest{}
		var fernTestValuePerPage *int
		obj.SetPerPage(fernTestValuePerPage)
		assert.Equal(t, fernTestValuePerPage, obj.PerPage)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPage", func(t *testing.T) {
		obj := &ListVanityNameserversRequest{}
		var fernTestValuePage *int
		obj.SetPage(fernTestValuePage)
		assert.Equal(t, fernTestValuePage, obj.Page)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitListVanityNameserversRequest(t *testing.T) {
	t.Run("SetDomainName_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListVanityNameserversRequest{}
		var fernTestValueDomainName string

		// Act
		obj.SetDomainName(fernTestValueDomainName)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPerPage_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListVanityNameserversRequest{}
		var fernTestValuePerPage *int

		// Act
		obj.SetPerPage(fernTestValuePerPage)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPage_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListVanityNameserversRequest{}
		var fernTestValuePage *int

		// Act
		obj.SetPage(fernTestValuePage)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersUpdateVanityNameserverBody(t *testing.T) {
	t.Run("SetDomainName", func(t *testing.T) {
		obj := &UpdateVanityNameserverBody{}
		var fernTestValueDomainName string
		obj.SetDomainName(fernTestValueDomainName)
		assert.Equal(t, fernTestValueDomainName, obj.DomainName)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetHostname", func(t *testing.T) {
		obj := &UpdateVanityNameserverBody{}
		var fernTestValueHostname string
		obj.SetHostname(fernTestValueHostname)
		assert.Equal(t, fernTestValueHostname, obj.Hostname)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetIps", func(t *testing.T) {
		obj := &UpdateVanityNameserverBody{}
		var fernTestValueIps []string
		obj.SetIps(fernTestValueIps)
		assert.Equal(t, fernTestValueIps, obj.Ips)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitUpdateVanityNameserverBody(t *testing.T) {
	t.Run("SetDomainName_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UpdateVanityNameserverBody{}
		var fernTestValueDomainName string

		// Act
		obj.SetDomainName(fernTestValueDomainName)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetHostname_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UpdateVanityNameserverBody{}
		var fernTestValueHostname string

		// Act
		obj.SetHostname(fernTestValueHostname)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetIps_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UpdateVanityNameserverBody{}
		var fernTestValueIps []string

		// Act
		obj.SetIps(fernTestValueIps)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersListVanityNameserversResponse(t *testing.T) {
	t.Run("SetLastPage", func(t *testing.T) {
		obj := &ListVanityNameserversResponse{}
		var fernTestValueLastPage *int
		obj.SetLastPage(fernTestValueLastPage)
		assert.Equal(t, fernTestValueLastPage, obj.LastPage)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetNextPage", func(t *testing.T) {
		obj := &ListVanityNameserversResponse{}
		var fernTestValueNextPage *int
		obj.SetNextPage(fernTestValueNextPage)
		assert.Equal(t, fernTestValueNextPage, obj.NextPage)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetVanityNameservers", func(t *testing.T) {
		obj := &ListVanityNameserversResponse{}
		var fernTestValueVanityNameservers []*VanityNameserverResponse
		obj.SetVanityNameservers(fernTestValueVanityNameservers)
		assert.Equal(t, fernTestValueVanityNameservers, obj.VanityNameservers)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersListVanityNameserversResponse(t *testing.T) {
	t.Run("GetLastPage", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListVanityNameserversResponse{}
		var expected *int
		obj.LastPage = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetLastPage(), "getter should return the property value")
	})

	t.Run("GetLastPage_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListVanityNameserversResponse{}
		obj.LastPage = nil

		// Act & Assert
		assert.Nil(t, obj.GetLastPage(), "getter should return nil when property is nil")
	})

	t.Run("GetLastPage_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListVanityNameserversResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetLastPage() // Should return zero value
	})

	t.Run("GetNextPage", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListVanityNameserversResponse{}
		var expected *int
		obj.NextPage = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetNextPage(), "getter should return the property value")
	})

	t.Run("GetNextPage_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListVanityNameserversResponse{}
		obj.NextPage = nil

		// Act & Assert
		assert.Nil(t, obj.GetNextPage(), "getter should return nil when property is nil")
	})

	t.Run("GetNextPage_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListVanityNameserversResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetNextPage() // Should return zero value
	})

	t.Run("GetVanityNameservers", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListVanityNameserversResponse{}
		var expected []*VanityNameserverResponse
		obj.VanityNameservers = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetVanityNameservers(), "getter should return the property value")
	})

	t.Run("GetVanityNameservers_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListVanityNameserversResponse{}
		obj.VanityNameservers = nil

		// Act & Assert
		assert.Nil(t, obj.GetVanityNameservers(), "getter should return nil when property is nil")
	})

	t.Run("GetVanityNameservers_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListVanityNameserversResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetVanityNameservers() // Should return zero value
	})

}

func TestSettersMarkExplicitListVanityNameserversResponse(t *testing.T) {
	t.Run("SetLastPage_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListVanityNameserversResponse{}
		var fernTestValueLastPage *int

		// Act
		obj.SetLastPage(fernTestValueLastPage)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetNextPage_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListVanityNameserversResponse{}
		var fernTestValueNextPage *int

		// Act
		obj.SetNextPage(fernTestValueNextPage)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetVanityNameservers_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListVanityNameserversResponse{}
		var fernTestValueVanityNameservers []*VanityNameserverResponse

		// Act
		obj.SetVanityNameservers(fernTestValueVanityNameservers)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersVanityNameserverResponse(t *testing.T) {
	t.Run("SetHostname", func(t *testing.T) {
		obj := &VanityNameserverResponse{}
		var fernTestValueHostname *string
		obj.SetHostname(fernTestValueHostname)
		assert.Equal(t, fernTestValueHostname, obj.Hostname)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetDomainName", func(t *testing.T) {
		obj := &VanityNameserverResponse{}
		var fernTestValueDomainName string
		obj.SetDomainName(fernTestValueDomainName)
		assert.Equal(t, fernTestValueDomainName, obj.DomainName)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetIps", func(t *testing.T) {
		obj := &VanityNameserverResponse{}
		var fernTestValueIps []string
		obj.SetIps(fernTestValueIps)
		assert.Equal(t, fernTestValueIps, obj.Ips)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersVanityNameserverResponse(t *testing.T) {
	t.Run("GetHostname", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &VanityNameserverResponse{}
		var expected *string
		obj.Hostname = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetHostname(), "getter should return the property value")
	})

	t.Run("GetHostname_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &VanityNameserverResponse{}
		obj.Hostname = nil

		// Act & Assert
		assert.Nil(t, obj.GetHostname(), "getter should return nil when property is nil")
	})

	t.Run("GetHostname_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *VanityNameserverResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetHostname() // Should return zero value
	})

	t.Run("GetDomainName", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &VanityNameserverResponse{}
		var expected string
		obj.DomainName = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetDomainName(), "getter should return the property value")
	})

	t.Run("GetDomainName_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *VanityNameserverResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetDomainName() // Should return zero value
	})

	t.Run("GetIps", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &VanityNameserverResponse{}
		var expected []string
		obj.Ips = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetIps(), "getter should return the property value")
	})

	t.Run("GetIps_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &VanityNameserverResponse{}
		obj.Ips = nil

		// Act & Assert
		assert.Nil(t, obj.GetIps(), "getter should return nil when property is nil")
	})

	t.Run("GetIps_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *VanityNameserverResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetIps() // Should return zero value
	})

}

func TestSettersMarkExplicitVanityNameserverResponse(t *testing.T) {
	t.Run("SetHostname_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &VanityNameserverResponse{}
		var fernTestValueHostname *string

		// Act
		obj.SetHostname(fernTestValueHostname)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetDomainName_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &VanityNameserverResponse{}
		var fernTestValueDomainName string

		// Act
		obj.SetDomainName(fernTestValueDomainName)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetIps_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &VanityNameserverResponse{}
		var fernTestValueIps []string

		// Act
		obj.SetIps(fernTestValueIps)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestJSONMarshalingListVanityNameserversResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListVanityNameserversResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled ListVanityNameserversResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj ListVanityNameserversResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj ListVanityNameserversResponse
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingVanityNameserverResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &VanityNameserverResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled VanityNameserverResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj VanityNameserverResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj VanityNameserverResponse
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestStringListVanityNameserversResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &ListVanityNameserversResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListVanityNameserversResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringVanityNameserverResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &VanityNameserverResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *VanityNameserverResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestExtraPropertiesListVanityNameserversResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &ListVanityNameserversResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListVanityNameserversResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesVanityNameserverResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &VanityNameserverResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *VanityNameserverResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}
