// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/namedotcom/core-api-go/internal"
	big "math/big"
)

var (
	createVanityNameserverBodyFieldDomainName = big.NewInt(1 << 0)
	createVanityNameserverBodyFieldHostname   = big.NewInt(1 << 1)
	createVanityNameserverBodyFieldIps        = big.NewInt(1 << 2)
)

type CreateVanityNameserverBody struct {
	// The domain name to create a vanity nameserver for.
	DomainName string `json:"-" url:"-"`
	// The subdomain portion of the nameserver hostname. The domain portion will be  taken from the URL path. For example, to create 'ns1.example.com', specify 'ns1'  when calling the endpoint for the domain 'example.com'.
	Hostname string `json:"hostname" url:"-"`
	// IPs is a list of IP addresses that are used for glue records for this nameserver. These should be valid IPv4 or IPv6 addresses.
	Ips []string `json:"ips" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CreateVanityNameserverBody) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetDomainName sets the DomainName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateVanityNameserverBody) SetDomainName(domainName string) {
	c.DomainName = domainName
	c.require(createVanityNameserverBodyFieldDomainName)
}

// SetHostname sets the Hostname field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateVanityNameserverBody) SetHostname(hostname string) {
	c.Hostname = hostname
	c.require(createVanityNameserverBodyFieldHostname)
}

// SetIps sets the Ips field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateVanityNameserverBody) SetIps(ips []string) {
	c.Ips = ips
	c.require(createVanityNameserverBodyFieldIps)
}

func (c *CreateVanityNameserverBody) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateVanityNameserverBody
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*c = CreateVanityNameserverBody(body)
	return nil
}

func (c *CreateVanityNameserverBody) MarshalJSON() ([]byte, error) {
	type embed CreateVanityNameserverBody
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	deleteVanityNameserverRequestFieldDomainName = big.NewInt(1 << 0)
	deleteVanityNameserverRequestFieldHostname   = big.NewInt(1 << 1)
)

type DeleteVanityNameserverRequest struct {
	// The domain name associated with the vanity nameserver.
	DomainName string `json:"-" url:"-"`
	// The hostname of the vanity nameserver to delete.
	Hostname string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (d *DeleteVanityNameserverRequest) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetDomainName sets the DomainName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteVanityNameserverRequest) SetDomainName(domainName string) {
	d.DomainName = domainName
	d.require(deleteVanityNameserverRequestFieldDomainName)
}

// SetHostname sets the Hostname field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteVanityNameserverRequest) SetHostname(hostname string) {
	d.Hostname = hostname
	d.require(deleteVanityNameserverRequestFieldHostname)
}

var (
	getVanityNameserverRequestFieldDomainName = big.NewInt(1 << 0)
	getVanityNameserverRequestFieldHostname   = big.NewInt(1 << 1)
)

type GetVanityNameserverRequest struct {
	// The domain name associated with the vanity nameserver.
	DomainName string `json:"-" url:"-"`
	// The hostname of the vanity nameserver to retrieve.
	Hostname string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetVanityNameserverRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetDomainName sets the DomainName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetVanityNameserverRequest) SetDomainName(domainName string) {
	g.DomainName = domainName
	g.require(getVanityNameserverRequestFieldDomainName)
}

// SetHostname sets the Hostname field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetVanityNameserverRequest) SetHostname(hostname string) {
	g.Hostname = hostname
	g.require(getVanityNameserverRequestFieldHostname)
}

var (
	listVanityNameserversRequestFieldDomainName = big.NewInt(1 << 0)
	listVanityNameserversRequestFieldPerPage    = big.NewInt(1 << 1)
	listVanityNameserversRequestFieldPage       = big.NewInt(1 << 2)
)

type ListVanityNameserversRequest struct {
	// The domain name to list vanity nameservers for.
	DomainName string `json:"-" url:"-"`
	// The number of records to return per page. Defaults to 500.
	PerPage *int `json:"-" url:"perPage,omitempty"`
	// The page number to return.
	Page *int `json:"-" url:"page,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListVanityNameserversRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetDomainName sets the DomainName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListVanityNameserversRequest) SetDomainName(domainName string) {
	l.DomainName = domainName
	l.require(listVanityNameserversRequestFieldDomainName)
}

// SetPerPage sets the PerPage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListVanityNameserversRequest) SetPerPage(perPage *int) {
	l.PerPage = perPage
	l.require(listVanityNameserversRequestFieldPerPage)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListVanityNameserversRequest) SetPage(page *int) {
	l.Page = page
	l.require(listVanityNameserversRequestFieldPage)
}

var (
	updateVanityNameserverBodyFieldDomainName = big.NewInt(1 << 0)
	updateVanityNameserverBodyFieldHostname   = big.NewInt(1 << 1)
	updateVanityNameserverBodyFieldIps        = big.NewInt(1 << 2)
)

type UpdateVanityNameserverBody struct {
	// The domain name associated with the vanity nameserver.
	DomainName string `json:"-" url:"-"`
	// The hostname of the vanity nameserver to update.
	Hostname string `json:"-" url:"-"`
	// IPs is the updated list of IP addresses to be used for glue records for this vanity nameserver. Providing an empty array will remove all existing IPs.
	Ips []string `json:"ips" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (u *UpdateVanityNameserverBody) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetDomainName sets the DomainName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateVanityNameserverBody) SetDomainName(domainName string) {
	u.DomainName = domainName
	u.require(updateVanityNameserverBodyFieldDomainName)
}

// SetHostname sets the Hostname field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateVanityNameserverBody) SetHostname(hostname string) {
	u.Hostname = hostname
	u.require(updateVanityNameserverBodyFieldHostname)
}

// SetIps sets the Ips field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateVanityNameserverBody) SetIps(ips []string) {
	u.Ips = ips
	u.require(updateVanityNameserverBodyFieldIps)
}

func (u *UpdateVanityNameserverBody) UnmarshalJSON(data []byte) error {
	type unmarshaler UpdateVanityNameserverBody
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*u = UpdateVanityNameserverBody(body)
	return nil
}

func (u *UpdateVanityNameserverBody) MarshalJSON() ([]byte, error) {
	type embed UpdateVanityNameserverBody
	var marshaler = struct {
		embed
	}{
		embed: embed(*u),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, u.explicitFields)
	return json.Marshal(explicitMarshaler)
}

// ListVanityNameserversResponse returns the list of vanity nameservers for the domain.
var (
	listVanityNameserversResponseFieldLastPage          = big.NewInt(1 << 0)
	listVanityNameserversResponseFieldNextPage          = big.NewInt(1 << 1)
	listVanityNameserversResponseFieldVanityNameservers = big.NewInt(1 << 2)
)

type ListVanityNameserversResponse struct {
	// LastPage is the identifier for the final page of results. It is only populated if there is another page of results after the current page. If no further pages exist, this field will be null.
	LastPage *int `json:"lastPage,omitempty" url:"lastPage,omitempty"`
	// NextPage is the identifier for the next page of results. It is only populated if there is another page of results after the current page. If no further pages exist, this field will be null.
	NextPage *int `json:"nextPage,omitempty" url:"nextPage,omitempty"`
	// VanityNameservers is the list of vanity nameservers associated with the domain. If no vanity nameservers are configured, this will be an empty array.
	VanityNameservers []*VanityNameserverResponse `json:"vanityNameservers" url:"vanityNameservers"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *ListVanityNameserversResponse) GetLastPage() *int {
	if l == nil {
		return nil
	}
	return l.LastPage
}

func (l *ListVanityNameserversResponse) GetNextPage() *int {
	if l == nil {
		return nil
	}
	return l.NextPage
}

func (l *ListVanityNameserversResponse) GetVanityNameservers() []*VanityNameserverResponse {
	if l == nil {
		return nil
	}
	return l.VanityNameservers
}

func (l *ListVanityNameserversResponse) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *ListVanityNameserversResponse) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetLastPage sets the LastPage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListVanityNameserversResponse) SetLastPage(lastPage *int) {
	l.LastPage = lastPage
	l.require(listVanityNameserversResponseFieldLastPage)
}

// SetNextPage sets the NextPage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListVanityNameserversResponse) SetNextPage(nextPage *int) {
	l.NextPage = nextPage
	l.require(listVanityNameserversResponseFieldNextPage)
}

// SetVanityNameservers sets the VanityNameservers field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListVanityNameserversResponse) SetVanityNameservers(vanityNameservers []*VanityNameserverResponse) {
	l.VanityNameservers = vanityNameservers
	l.require(listVanityNameserversResponseFieldVanityNameservers)
}

func (l *ListVanityNameserversResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ListVanityNameserversResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = ListVanityNameserversResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *ListVanityNameserversResponse) MarshalJSON() ([]byte, error) {
	type embed ListVanityNameserversResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *ListVanityNameserversResponse) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}

// VanityNameserver response schema with full hostname
var (
	vanityNameserverResponseFieldHostname   = big.NewInt(1 << 0)
	vanityNameserverResponseFieldDomainName = big.NewInt(1 << 1)
	vanityNameserverResponseFieldIps        = big.NewInt(1 << 2)
)

type VanityNameserverResponse struct {
	// Hostname is the fully qualified domain name (FQDN) of the vanity nameserver. It must be a subdomain of the domain specified in 'domainName'.
	Hostname *string `json:"hostname,omitempty" url:"hostname,omitempty"`
	// DomainName is the root domain for which this vanity nameserver is created. For example, if the hostname is 'ns1.example.com', the domainName would be 'example.com'.
	DomainName string `json:"domainName" url:"domainName"`
	// IPs is a list of IP addresses that are used for glue records for this vanity nameserver. These should be valid IPv4 or IPv6 addresses.
	Ips []string `json:"ips" url:"ips"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (v *VanityNameserverResponse) GetHostname() *string {
	if v == nil {
		return nil
	}
	return v.Hostname
}

func (v *VanityNameserverResponse) GetDomainName() string {
	if v == nil {
		return ""
	}
	return v.DomainName
}

func (v *VanityNameserverResponse) GetIps() []string {
	if v == nil {
		return nil
	}
	return v.Ips
}

func (v *VanityNameserverResponse) GetExtraProperties() map[string]interface{} {
	if v == nil {
		return nil
	}
	return v.extraProperties
}

func (v *VanityNameserverResponse) require(field *big.Int) {
	if v.explicitFields == nil {
		v.explicitFields = big.NewInt(0)
	}
	v.explicitFields.Or(v.explicitFields, field)
}

// SetHostname sets the Hostname field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *VanityNameserverResponse) SetHostname(hostname *string) {
	v.Hostname = hostname
	v.require(vanityNameserverResponseFieldHostname)
}

// SetDomainName sets the DomainName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *VanityNameserverResponse) SetDomainName(domainName string) {
	v.DomainName = domainName
	v.require(vanityNameserverResponseFieldDomainName)
}

// SetIps sets the Ips field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *VanityNameserverResponse) SetIps(ips []string) {
	v.Ips = ips
	v.require(vanityNameserverResponseFieldIps)
}

func (v *VanityNameserverResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler VanityNameserverResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*v = VanityNameserverResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *v)
	if err != nil {
		return err
	}
	v.extraProperties = extraProperties
	v.rawJSON = json.RawMessage(data)
	return nil
}

func (v *VanityNameserverResponse) MarshalJSON() ([]byte, error) {
	type embed VanityNameserverResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*v),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, v.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (v *VanityNameserverResponse) String() string {
	if v == nil {
		return "<nil>"
	}
	if len(v.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(v.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(v); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", v)
}
