// Code generated by Fern. DO NOT EDIT.

package contact_verification_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	http "net/http"
	os "os"
	testing "testing"

	coreapigo "github.com/namedotcom/core-api-go"
	client "github.com/namedotcom/core-api-go/client"
	option "github.com/namedotcom/core-api-go/option"
	require "github.com/stretchr/testify/require"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]any,
	expected int,
) {
	wiremockURL := os.Getenv("WIREMOCK_URL")
	if wiremockURL == "" {
		wiremockURL = "http://localhost:8080"
	}
	WiremockAdminURL := wiremockURL + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			switch v := value.(type) {
			case string:
				reqBody.WriteString(`":{"equalTo":"`)
				reqBody.WriteString(v)
				reqBody.WriteString(`"}`)
			case []string:
				reqBody.WriteString(`":{"hasExactly":[`)
				for i, item := range v {
					if i > 0 {
						reqBody.WriteString(",")
					}
					reqBody.WriteString(`{"equalTo":"`)
					reqBody.WriteString(item)
					reqBody.WriteString(`"}`)
				}
				reqBody.WriteString(`]}`)
			}
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestContactVerificationUnverifiedContactsListWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewNamecom(
		option.WithBaseURL(WireMockBaseURL),
		option.WithBasicAuth("test-username", "test-password"),
	)
	request := &coreapigo.UnverifiedContactsListRequest{
		PerPage: coreapigo.Int(
			100,
		),
		Page: coreapigo.Int(
			2,
		),
	}
	_, invocationErr := client.ContactVerification.UnverifiedContactsList(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestContactVerificationUnverifiedContactsListWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestContactVerificationUnverifiedContactsListWithWireMock", "GET", "/core/v1/contacts/unverified", map[string]interface{}{"perPage": "100", "page": "2"}, 1)
}

func TestContactVerificationVerifyContactWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewNamecom(
		option.WithBaseURL(WireMockBaseURL),
		option.WithBasicAuth("test-username", "test-password"),
	)
	request := &coreapigo.VerifyContactRequest{
		VerificationID: 1,
		IdempotencyKey: coreapigo.String(
			"083910ef-04e4-4bd1-a0bf-3737fe005ca8",
		),
		Body: &coreapigo.EmptyObject{},
	}
	invocationErr := client.ContactVerification.VerifyContact(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestContactVerificationVerifyContactWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestContactVerificationVerifyContactWithWireMock", "POST", "/core/v1/contacts/verify/1", nil, 1)
}

func TestContactVerificationResendContactVerificationEmailWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewNamecom(
		option.WithBaseURL(WireMockBaseURL),
		option.WithBasicAuth("test-username", "test-password"),
	)
	request := &coreapigo.ResendContactVerificationEmailRequest{
		VerificationID: 1,
		IdempotencyKey: coreapigo.String(
			"083910ef-04e4-4bd1-a0bf-3737fe005ca8",
		),
		Body: &coreapigo.EmptyObject{},
	}
	_, invocationErr := client.ContactVerification.ResendContactVerificationEmail(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestContactVerificationResendContactVerificationEmailWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestContactVerificationResendContactVerificationEmailWithWireMock", "POST", "/core/v1/contacts/verify/1:resend", nil, 1)
}
