// Code generated by Fern. DO NOT EDIT.

package email_forwardings_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	http "net/http"
	os "os"
	testing "testing"

	coreapigo "github.com/namedotcom/core-api-go"
	client "github.com/namedotcom/core-api-go/client"
	option "github.com/namedotcom/core-api-go/option"
	require "github.com/stretchr/testify/require"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]any,
	expected int,
) {
	wiremockURL := os.Getenv("WIREMOCK_URL")
	if wiremockURL == "" {
		wiremockURL = "http://localhost:8080"
	}
	WiremockAdminURL := wiremockURL + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			switch v := value.(type) {
			case string:
				reqBody.WriteString(`":{"equalTo":"`)
				reqBody.WriteString(v)
				reqBody.WriteString(`"}`)
			case []string:
				reqBody.WriteString(`":{"hasExactly":[`)
				for i, item := range v {
					if i > 0 {
						reqBody.WriteString(",")
					}
					reqBody.WriteString(`{"equalTo":"`)
					reqBody.WriteString(item)
					reqBody.WriteString(`"}`)
				}
				reqBody.WriteString(`]}`)
			}
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestEmailForwardingsListEmailForwardingsWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewNamecom(
		option.WithBaseURL(WireMockBaseURL),
		option.WithBasicAuth("test-username", "test-password"),
	)
	request := &coreapigo.ListEmailForwardingsRequest{
		DomainName: "domainName",
		PerPage: coreapigo.Int(
			100,
		),
		Page: coreapigo.Int(
			1,
		),
	}
	_, invocationErr := client.EmailForwardings.ListEmailForwardings(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestEmailForwardingsListEmailForwardingsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestEmailForwardingsListEmailForwardingsWithWireMock", "GET", "/core/v1/domains/domainName/email/forwarding", map[string]interface{}{"perPage": "100", "page": "1"}, 1)
}

func TestEmailForwardingsCreateEmailForwardingWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewNamecom(
		option.WithBaseURL(WireMockBaseURL),
		option.WithBasicAuth("test-username", "test-password"),
	)
	request := &coreapigo.CreateEmailForwardingRequest{
		DomainName: "example.com",
		EmailBox:   "admin",
		EmailTo:    "webmaster@example.com",
	}
	_, invocationErr := client.EmailForwardings.CreateEmailForwarding(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestEmailForwardingsCreateEmailForwardingWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestEmailForwardingsCreateEmailForwardingWithWireMock", "POST", "/core/v1/domains/example.com/email/forwarding", nil, 1)
}

func TestEmailForwardingsGetEmailForwardingWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewNamecom(
		option.WithBaseURL(WireMockBaseURL),
		option.WithBasicAuth("test-username", "test-password"),
	)
	request := &coreapigo.GetEmailForwardingRequest{
		DomainName: "domainName",
		EmailBox:   "emailBox",
	}
	_, invocationErr := client.EmailForwardings.GetEmailForwarding(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestEmailForwardingsGetEmailForwardingWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestEmailForwardingsGetEmailForwardingWithWireMock", "GET", "/core/v1/domains/domainName/email/forwarding/emailBox", nil, 1)
}

func TestEmailForwardingsUpdateEmailForwardingWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewNamecom(
		option.WithBaseURL(WireMockBaseURL),
		option.WithBasicAuth("test-username", "test-password"),
	)
	request := &coreapigo.EmailForwardingsUpdateEmailForwardingBody{
		DomainName: "domainName",
		EmailBox:   "emailBox",
		EmailTo:    "emailTo",
	}
	_, invocationErr := client.EmailForwardings.UpdateEmailForwarding(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestEmailForwardingsUpdateEmailForwardingWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestEmailForwardingsUpdateEmailForwardingWithWireMock", "PUT", "/core/v1/domains/domainName/email/forwarding/emailBox", nil, 1)
}

func TestEmailForwardingsDeleteEmailForwardingWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewNamecom(
		option.WithBaseURL(WireMockBaseURL),
		option.WithBasicAuth("test-username", "test-password"),
	)
	request := &coreapigo.DeleteEmailForwardingRequest{
		DomainName: "domainName",
		EmailBox:   "emailBox",
	}
	invocationErr := client.EmailForwardings.DeleteEmailForwarding(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestEmailForwardingsDeleteEmailForwardingWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestEmailForwardingsDeleteEmailForwardingWithWireMock", "DELETE", "/core/v1/domains/domainName/email/forwarding/emailBox", nil, 1)
}
