// Code generated by Fern. DO NOT EDIT.

package premiumdomains

import (
	context "context"

	coreapigo "github.com/namedotcom/core-api-go"
	core "github.com/namedotcom/core-api-go/core"
	internal "github.com/namedotcom/core-api-go/internal"
	option "github.com/namedotcom/core-api-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Gets a pre-signed URL that will allow a user to download a list of premium domains, with their registration and renewal pricing.
// **Please Note:** The pre-signed URL will only be valid for 10 minutes. This endpoint is only available to approved reseller accounts. Contact name.com support to request access.
//
// Example:
//
//	client.PremiumDomains.PremiumDomainLists(
//	    context.TODO(),
//	)
func (c *Client) PremiumDomainLists(
	ctx context.Context,
	opts ...option.RequestOption,
) (*coreapigo.PremiumDomainsDownloadResponse, error) {
	response, err := c.WithRawResponse.PremiumDomainLists(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
