// Code generated by Fern. DO NOT EDIT.

package transfers

import (
	context "context"

	coreapigo "github.com/namedotcom/core-api-go"
	core "github.com/namedotcom/core-api-go/core"
	internal "github.com/namedotcom/core-api-go/internal"
	option "github.com/namedotcom/core-api-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Returns all domain transfer requests for the account, including in-progress and recent transfers.
func (c *Client) ListTransfers(
	ctx context.Context,
	request *coreapigo.ListTransfersRequest,
	opts ...option.RequestOption,
) (*coreapigo.ListTransfersResponse, error) {
	response, err := c.WithRawResponse.ListTransfers(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Initiates a domain transfer into your name.com account from another registrar. You must provide the domain name and its valid transfer authorization code (EPP code). The domain must not be locked or under any transfer restrictions (e.g. clientTransferProhibited). If successful, the transfer is submitted and tracked through the ICANN transfer process. Once a transfer has been created, you can track its progress via the [GetTransfer](/api/v1/reference/transfers/get-transfer) endpoint.
// **Transfer pricing:** Omit `purchasePrice` for standard (non-premium) transfers. For premium transfers, pass `transferPrice` from [Get Pricing For Domain](/api/v1/reference/domains/get-pricing-for-domain) as `purchasePrice`. If sent, it must match Get Pricing `transferPrice` exactly or the request will fail. Premium transfers without `purchasePrice` will fail. See the [Domain pricing guide](/guides/domain-pricing) for how [Get Pricing](/api/v1/reference/domains/get-pricing-for-domain) `transferPrice` relates to the `years` query parameter.
func (c *Client) CreateTransfer(
	ctx context.Context,
	request *coreapigo.CreateTransferRequest,
	opts ...option.RequestOption,
) (*coreapigo.CreateTransferResponse, error) {
	response, err := c.WithRawResponse.CreateTransfer(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieves details of a specific domain transfer request.
func (c *Client) GetTransfer(
	ctx context.Context,
	request *coreapigo.GetTransferRequest,
	opts ...option.RequestOption,
) (*coreapigo.Transfer, error) {
	response, err := c.WithRawResponse.GetTransfer(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Cancels a pending transfer request. This can be used if the transfer was initiated in error or if the authorization code provided was incorrect.
// The price of the transfer will refund the amount to account credit.
//
// Cancelable statuses:
// - pending
// - submitting_transfer
// - pending_new_auth_code
// - pending_unlock
// - pending_registry_unlock
// - rejected
//
// Non-cancelable statuses:
// - pending_transfer
// - pending_insert
// - completed
// - failed
// - canceled
// - canceled_pending_refund
func (c *Client) CancelTransfer(
	ctx context.Context,
	request *coreapigo.CancelTransferRequest,
	opts ...option.RequestOption,
) (*coreapigo.Transfer, error) {
	response, err := c.WithRawResponse.CancelTransfer(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Cancels an outbound transfer for the given domain. Use this when the domain is being transferred out of name.com (losing registrar) to another (gaining) registrar and the registrant or reseller wants to cancel that transfer.
// On success, subscribers receive `domain.transfer_out.status_change` with status `canceled`.
// The endpoint validates that the domain exists and belongs to the authenticated account. Only domains in a pending transfer (out) state can be canceled.
func (c *Client) CancelOutboundTransfer(
	ctx context.Context,
	request *coreapigo.CancelOutboundTransferRequest,
	opts ...option.RequestOption,
) (*coreapigo.CancelTransferOutResponse, error) {
	response, err := c.WithRawResponse.CancelOutboundTransfer(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Pulls a domain from another [name.com](https://www.name.com) account into your reseller (gaining) account using a valid authorization code. This is an **internal** name.com-to-name.com move; it is separate from [Create Transfer](/api/v1/reference/transfers/create-transfer), which brings domains in from **external** registrars.
// Check if a TLD is eligible for internal transfer in by calling [Tld Requirements](/api/v1/reference/domaininfo/requirementsV2) for the TLD and checking property `supportsInternalTransfer`.
// This API is only available to approved reseller accounts. Contact name.com support to request access.
// #### Losing account (dashboard only)
// The party that holds the domain today must use the name.com dashboard on the **losing** account to **unlock** the domain (remove registrar transfer lock) and to **copy the authorization code** to provide to your integration. This endpoint does not unlock the domain or retrieve the auth code for the losing account.
// #### Gaining account (this API)
// Call this endpoint with `domainName`, `authCode`, and optional `contacts` using the **gaining** reseller's API credentials.
// #### Contacts and post-transfer lock
// If `contacts` is omitted, the gaining account's default contacts are applied. If `contacts` is provided, any roles included in the request are applied and omitted roles use the gaining account's default contacts (same pattern as [Create Domain](/api/v1/reference/domains/create-domain) and [Set Contacts](/api/v1/reference/domains/set-contacts)). The 60-day contact-change transfer lock is enforced based on the **gaining** account's settings, consistent with Set Contacts.
// #### Access
// Restricted to approved enterprise resellers; other callers receive `403 Forbidden`.
func (c *Client) CreateInternalTransferIn(
	ctx context.Context,
	request *coreapigo.CreateInternalTransferInRequest,
	opts ...option.RequestOption,
) (*coreapigo.DomainResponsePayload, error) {
	response, err := c.WithRawResponse.CreateInternalTransferIn(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Returns whether a domain is currently registered at [name.com](https://www.name.com) and whether the TLD supports internal transfer between name.com accounts. Use this to decide whether to send your user through the [Create Transfer](/api/v1/reference/transfers/create-transfer) external transfer flow or the [Create Internal Transfer In](/api/v1/reference/transfers/create-internal-transfer-in) flow before initiating a transfer-in.
//
// #### Response semantics
//
// `atName` is `true` if the domain is currently registered at name.com in any account. This information is also publicly available via RDAP.
//
// `supportsInternalTransfer` mirrors the TLD-level value returned by [Tld Requirements](/api/v1/reference/domain-info/get-specific-tld-requirements). It indicates whether the TLD is eligible for internal transfer between name.com accounts. It does not reflect per-account allowlist eligibility — if your account is not allowlisted for internal transfer in, calling [Create Internal Transfer In](/api/v1/reference/transfers/create-internal-transfer-in) will return `403 Forbidden`.
//
// #### Privacy
//
// This endpoint never reveals which account a domain is in. To check whether a domain is in your own account, use [Get Domain](/api/v1/reference/domains/get-domain) instead.
func (c *Client) GetTransferEligibility(
	ctx context.Context,
	request *coreapigo.GetTransferEligibilityRequest,
	opts ...option.RequestOption,
) (*coreapigo.TransferEligibilityResponse, error) {
	response, err := c.WithRawResponse.GetTransferEligibility(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
