// Code generated by Fern. DO NOT EDIT.

package emailforwardings

import (
	context "context"
	http "net/http"

	coreapigo "github.com/namedotcom/core-api-go"
	core "github.com/namedotcom/core-api-go/core"
	internal "github.com/namedotcom/core-api-go/internal"
	option "github.com/namedotcom/core-api-go/option"
)

type RawClient struct {
	baseURL string
	caller  *internal.Caller
	options *core.RequestOptions
}

func NewRawClient(options *core.RequestOptions) *RawClient {
	return &RawClient{
		options: options,
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

func (r *RawClient) ListEmailForwardings(
	ctx context.Context,
	request *coreapigo.ListEmailForwardingsRequest,
	opts ...option.RequestOption,
) (*core.Response[*coreapigo.ListEmailForwardingsResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.dev.name.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/core/v1/domains/%v/email/forwarding",
		request.DomainName,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *coreapigo.ListEmailForwardingsResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(coreapigo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*coreapigo.ListEmailForwardingsResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) CreateEmailForwarding(
	ctx context.Context,
	request *coreapigo.CreateEmailForwardingRequest,
	opts ...option.RequestOption,
) (*core.Response[*coreapigo.EmailForwarding], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.dev.name.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/core/v1/domains/%v/email/forwarding",
		request.DomainName,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *coreapigo.EmailForwarding
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(coreapigo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*coreapigo.EmailForwarding]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) GetEmailForwarding(
	ctx context.Context,
	request *coreapigo.GetEmailForwardingRequest,
	opts ...option.RequestOption,
) (*core.Response[*coreapigo.EmailForwarding], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.dev.name.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/core/v1/domains/%v/email/forwarding/%v",
		request.DomainName,
		request.EmailBox,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *coreapigo.EmailForwarding
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(coreapigo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*coreapigo.EmailForwarding]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) UpdateEmailForwarding(
	ctx context.Context,
	request *coreapigo.EmailForwardingsUpdateEmailForwardingBody,
	opts ...option.RequestOption,
) (*core.Response[*coreapigo.EmailForwarding], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.dev.name.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/core/v1/domains/%v/email/forwarding/%v",
		request.DomainName,
		request.EmailBox,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *coreapigo.EmailForwarding
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPut,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(coreapigo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*coreapigo.EmailForwarding]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) DeleteEmailForwarding(
	ctx context.Context,
	request *coreapigo.DeleteEmailForwardingRequest,
	opts ...option.RequestOption,
) (*core.Response[any], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.dev.name.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/core/v1/domains/%v/email/forwarding/%v",
		request.DomainName,
		request.EmailBox,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodDelete,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			ErrorDecoder:    internal.NewErrorDecoder(coreapigo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[any]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       nil,
	}, nil
}
