// Code generated by Fern. DO NOT EDIT.

package core

import (
	fmt "fmt"
	http "net/http"
)

// IdempotentRequestOption adapts the behavior of an individual request.
type IdempotentRequestOption interface {
	applyIdempotentRequestOptions(*IdempotentRequestOptions)
}

// IdempotentRequestOptions defines all of the possible idempotent request options.
//
// This type is primarily used by the generated code and is not meant
// to be used directly; use the option package instead.
type IdempotentRequestOptions struct {
	*RequestOptions

	XIdempotencyKey *string
}

// NewIdempotentRequestOptions returns a new *IdempotentRequestOptions value.
//
// This function is primarily used by the generated code and is not meant
// to be used directly; use IdempotentRequestOption instead.
func NewIdempotentRequestOptions(opts ...IdempotentRequestOption) *IdempotentRequestOptions {
	options := &IdempotentRequestOptions{
		RequestOptions: NewRequestOptions(),
	}
	for _, opt := range opts {
		if requestOption, ok := opt.(RequestOption); ok {
			requestOption.applyRequestOptions(options.RequestOptions)
		}
		opt.applyIdempotentRequestOptions(options)
	}
	return options
}

// XIdempotencyKeyOption implements the RequestOption interface.
type XIdempotencyKeyOption struct {
	XIdempotencyKey *string
}

func (x *XIdempotencyKeyOption) applyIdempotentRequestOptions(opts *IdempotentRequestOptions) {
	opts.XIdempotencyKey = x.XIdempotencyKey
}

// ToHeader maps the configured request options into a http.Header used
// for the request.
func (i *IdempotentRequestOptions) ToHeader() http.Header {
	header := i.RequestOptions.ToHeader()
	if i.XIdempotencyKey != nil {
		header.Set("X-Idempotency-Key", fmt.Sprintf("*%v", *i.XIdempotencyKey))
	}
	return header
}
