// Code generated by Fern. DO NOT EDIT.

package accountinfo

import (
	context "context"
	http "net/http"

	coreapigo "github.com/namedotcom/core-api-go"
	core "github.com/namedotcom/core-api-go/core"
	internal "github.com/namedotcom/core-api-go/internal"
	option "github.com/namedotcom/core-api-go/option"
)

type RawClient struct {
	baseURL string
	caller  *internal.Caller
	options *core.RequestOptions
}

func NewRawClient(options *core.RequestOptions) *RawClient {
	return &RawClient{
		options: options,
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

func (r *RawClient) CheckAccountBalance(
	ctx context.Context,
	opts ...option.RequestOption,
) (*core.Response[*coreapigo.CheckAccountBalanceResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.dev.name.com",
	)
	endpointURL := baseURL + "/core/v1/accountinfo/balance"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *coreapigo.CheckAccountBalanceResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(coreapigo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*coreapigo.CheckAccountBalanceResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}
