// Code generated by Fern. DO NOT EDIT.

package option

import (
	core "github.com/namedotcom/core-api-go/core"
)

// IdempotentRequestOption adapts the behavior of an individual request.
type IdempotentRequestOption = core.IdempotentRequestOption

// WithXIdempotencyKey sets the xIdempotencyKey request header.
func WithXIdempotencyKey(xIdempotencyKey *string) *core.XIdempotencyKeyOption {
	return &core.XIdempotencyKeyOption{
		XIdempotencyKey: xIdempotencyKey,
	}
}
