// Code generated by Fern. DO NOT EDIT.

package domains

import (
	context "context"

	coreapigo "github.com/namedotcom/core-api-go"
	core "github.com/namedotcom/core-api-go/core"
	internal "github.com/namedotcom/core-api-go/internal"
	option "github.com/namedotcom/core-api-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Lists all domains in your account (basic details for each domain).
//
// Example:
//
//	request := &coreapigo.ListDomainsRequest{}
//	client.Domains.ListDomains(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) ListDomains(
	ctx context.Context,
	request *coreapigo.ListDomainsRequest,
	opts ...option.RequestOption,
) (*coreapigo.ListDomainsResponse, error) {
	response, err := c.WithRawResponse.ListDomains(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Registers a new domain under your account. You must provide `domain.domainName` at minimum.
// This endpoint is commonly used to programmatically onboard new domains through user signup flows or checkout experiences.
//
// If no contacts are passed in this request, the default contacts for your name.com account will be used.
//
// ### Create Domain pricing
//
// See the [Domain purchase pricing guide](/guides/domain-pricing) for the full reference.
// **Recommendation:** For most integrations, scope discovery to `purchaseType: registration`. Other purchase types are supported but add complexity — details in the guide above.
//
// **Discovery (required before create):** Call [Search](/api/v1/reference/domains/search) or [Check Availability](/api/v1/reference/domains/check-availability), not Get Pricing alone. Both return the same `SearchResult` fields (`purchaseType`, `purchasePrice`, `premium`, `purchasable`). [Zone Check](/api/v1/reference/domains/zone-check) is designed for rapid availability checks only; it is not sufficient to complete a purchase.
//
// ### Getting the price for Create Domain
//
// 1. **Search or Check Availability** → copy `purchaseType`, `premium`, note `purchasePrice`.
//
// 2. Branch on `purchaseType`:
//   - **`registration` + `premium: false`** — omit `purchasePrice` on create, set `years`. Optional: Get Pricing with same `years` to preview the total.
//   - **`registration` + `premium: true`** — Get Pricing with same `years` → pass `purchasePrice` exactly.
//   - **aftermarket / expiring / backorder** — use discovery `purchasePrice` (flat fee). Re-check discovery before create. Do not use Get Pricing for create price. `years` does not multiply price or guarantee registration length.
//
// 3. If `purchasePrice` is sent, it must match exactly or the request fails with `400` and `"Purchase price does not match"`.
//
// **Years on acquisition types:** For `aftermarket_s`, `aftermarket_b`, `aftermarket_i`, `expiring`, and `backorder`: omit `years` or pass the TLD default. Check `domain.expireDate` in the response; [Renew](/api/v1/reference/domains/renew-domain) to extend registration.
//
// ### Best Practices For Domain Creates
//
// In general, you should check that a domain is available prior to attempting to purchase a domain.
// You can use either the [checkAvailability](/api/v1/reference/domains/check-availability) endpoint, or the [Search](/api/v1/reference/domains/search) endpoint
// to confirm that a domain is purchasable.
//
// #### Important Note on Dropcatching and Abuse Prevention
//
// _The createDomain endpoint is designed for standard domain registrations and is not intended for automated dropcatching (i.e., mass or high-frequency attempts to register domains the moment they become available after expiration). The use of drop-catching tools or services to acquire expired domains is strictly prohibited. All domain acquisitions must go through approved channels to ensure fair and transparent access._
//
// #### Contact Verification
// When a new domain registration is created and a contact is submitted, name.com may need to validate the contact's email address in accordance with ICANN policy. This validation involves sending an email to the provided address, prompting the recipient to click a link to verify their email address.
//
// Example:
//
//	request := &coreapigo.CreateDomainRequest{
//	    Domain: &coreapigo.DomainCreatePayload{
//	        DomainName: coreapigo.String(
//	            "example.com",
//	        ),
//	    },
//	}
//	client.Domains.CreateDomain(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) CreateDomain(
	ctx context.Context,
	request *coreapigo.CreateDomainRequest,
	opts ...option.IdempotentRequestOption,
) (*coreapigo.CreateDomainResponse, error) {
	response, err := c.WithRawResponse.CreateDomain(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieves detailed information for a specific domain in your account.
//
// Example:
//
//	request := &coreapigo.GetDomainRequest{
//	    DomainName: "example.com",
//	}
//	client.Domains.GetDomain(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) GetDomain(
	ctx context.Context,
	request *coreapigo.GetDomainRequest,
	opts ...option.RequestOption,
) (*coreapigo.DomainResponsePayload, error) {
	response, err := c.WithRawResponse.GetDomain(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Allows updating of the autorenew, WhoIs Privacy and lock status of the specified domain. The request requires one, or any combination of the parameters in order to pass validation. If any of the requested updates failed, the domain will be returned to it's original state.
//
// Example:
//
//	request := &coreapigo.UpdateDomainRequest{
//	    DomainName: "domainName",
//	}
//	client.Domains.UpdateDomain(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) UpdateDomain(
	ctx context.Context,
	request *coreapigo.UpdateDomainRequest,
	opts ...option.RequestOption,
) (*coreapigo.DomainResponsePayload, error) {
	response, err := c.WithRawResponse.UpdateDomain(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Turns off automatic renewal for a domain. **DEPRECATED** This endpoint is deprecated in favor of the new UpdateDomain API. This will be removed in a future release.
//
// Example:
//
//	request := &coreapigo.DisableAutorenewRequest{
//	    DomainName: "example.com",
//	    Body: &coreapigo.EmptyObject{},
//	}
//	client.Domains.DisableAutorenew(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) DisableAutorenew(
	ctx context.Context,
	request *coreapigo.DisableAutorenewRequest,
	opts ...option.RequestOption,
) (*coreapigo.Domain, error) {
	response, err := c.WithRawResponse.DisableAutorenew(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Disables WHOIS privacy protection on a domain. **DEPRECATED** This endpoint is deprecated in favor of the new UpdateDomain API. This will be removed in a future release.
//
// Example:
//
//	request := &coreapigo.DisableWhoisPrivacyRequest{
//	    DomainName: "example.com",
//	    Body: &coreapigo.EmptyObject{},
//	}
//	client.Domains.DisableWhoisPrivacy(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) DisableWhoisPrivacy(
	ctx context.Context,
	request *coreapigo.DisableWhoisPrivacyRequest,
	opts ...option.RequestOption,
) (*coreapigo.Domain, error) {
	response, err := c.WithRawResponse.DisableWhoisPrivacy(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Turns on automatic renewal for a domain. **DEPRECATED** This endpoint is deprecated in favor of the new UpdateDomain API. This will be removed in a future release.
//
// Example:
//
//	request := &coreapigo.EnableAutorenewRequest{
//	    DomainName: "example.com",
//	    Body: &coreapigo.EmptyObject{},
//	}
//	client.Domains.EnableAutorenew(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) EnableAutorenew(
	ctx context.Context,
	request *coreapigo.EnableAutorenewRequest,
	opts ...option.RequestOption,
) (*coreapigo.Domain, error) {
	response, err := c.WithRawResponse.EnableAutorenew(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Enables WHOIS privacy protection on a domain. **DEPRECATED** This endpoint is deprecated in favor of the new UpdateDomain API. This will be removed in a future release.
//
// Example:
//
//	request := &coreapigo.EnableWhoisPrivacyRequest{
//	    DomainName: "domainName",
//	    Body: &coreapigo.EmptyObject{},
//	}
//	client.Domains.EnableWhoisPrivacy(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) EnableWhoisPrivacy(
	ctx context.Context,
	request *coreapigo.EnableWhoisPrivacyRequest,
	opts ...option.RequestOption,
) (*coreapigo.Domain, error) {
	response, err := c.WithRawResponse.EnableWhoisPrivacy(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieves the transfer authorization code (EPP code) for a domain.
//
// Example:
//
//	request := &coreapigo.GetAuthCodeForDomainRequest{
//	    DomainName: "domainName",
//	}
//	client.Domains.GetAuthCodeForDomain(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) GetAuthCodeForDomain(
	ctx context.Context,
	request *coreapigo.GetAuthCodeForDomainRequest,
	opts ...option.RequestOption,
) (*coreapigo.AuthCodeResponse, error) {
	response, err := c.WithRawResponse.GetAuthCodeForDomain(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Returns registration, renewal, and transfer pricing for a domain and term.
//
// **Not a discovery endpoint:** Does not return `purchaseType`. Cannot determine whether a domain is acquired via registration vs aftermarket/expiring/backorder — call [Search](/api/v1/reference/domains/search) or [Check Availability](/api/v1/reference/domains/check-availability) first.
//
// **Scope:** `purchasePrice` and `premium` reflect **standard and registry-premium registration** only. They do **not** return aftermarket, expiring, or backorder acquisition prices. For those types, use `purchasePrice` from Search or Check Availability.
//
// **Registration create (`purchaseType: registration`):** When create requires `purchasePrice` (registry premium), call with the **same** `years` you will send on create. Pass `purchasePrice` directly — it is the **total** for that term, not a per-year component.
//
// **Renew:** Pass `renewalPrice` as `purchasePrice` on [Renew Domain](/api/v1/reference/domains/renew-domain) for premium renewals — not for computing Create Domain totals.
//
// **Transfer:** Pass `transferPrice` as `purchasePrice` on [Create Transfer](/api/v1/reference/transfers/create-transfer) for premium transfers. The `years` query parameter does not affect `transferPrice`.
//
// See the [Domain pricing guide](/guides/domain-pricing) for the full workflow.
//
// Example:
//
//	request := &coreapigo.GetPricingForDomainRequest{
//	    DomainName: "domainName",
//	    Years: coreapigo.Int(
//	        2,
//	    ),
//	}
//	client.Domains.GetPricingForDomain(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) GetPricingForDomain(
	ctx context.Context,
	request *coreapigo.GetPricingForDomainRequest,
	opts ...option.RequestOption,
) (*coreapigo.PricingResponse, error) {
	response, err := c.WithRawResponse.GetPricingForDomain(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Locks a domain to prevent it from being transferred. **DEPRECATED** This endpoint is deprecated in favor of the new UpdateDomain API. This will be removed in a future release.
//
// Example:
//
//	request := &coreapigo.LockDomainRequest{
//	    DomainName: "example.com",
//	    Body: &coreapigo.EmptyObject{},
//	}
//	client.Domains.LockDomain(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) LockDomain(
	ctx context.Context,
	request *coreapigo.LockDomainRequest,
	opts ...option.RequestOption,
) (*coreapigo.Domain, error) {
	response, err := c.WithRawResponse.LockDomain(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Adds or renews WHOIS privacy protection for a domain. This is used to ensure personal contact details remain hidden from public WHOIS lookups.  If WHOIS privacy is already enabled, this will extend the protection. If it’s not yet active, this will enable the service.  WHOIS privacy is free for API users and does not add a fee.
//
// Example:
//
//	request := &coreapigo.DomainsPurchasePrivacyBody{
//	    DomainName: "domainName",
//	}
//	client.Domains.PurchasePrivacy(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) PurchasePrivacy(
	ctx context.Context,
	request *coreapigo.DomainsPurchasePrivacyBody,
	opts ...option.IdempotentRequestOption,
) (*coreapigo.PrivacyResponse, error) {
	response, err := c.WithRawResponse.PurchasePrivacy(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Renews an existing domain for an additional registration period. Include the domain name and renewal term. Omit `purchasePrice` for standard (non-premium) renewals. For premium renewals, pass `renewalPrice` from [Get Pricing](/api/v1/reference/domains/get-pricing-for-domain) with matching `years` as `purchasePrice`. Renewal pricing is separate from Create Domain registration/acquisition pricing. This is typically used to extend ownership before a domain’s expiration.
//
// Example:
//
//	request := &coreapigo.DomainsRenewDomainBody{
//	    DomainName: "domainName",
//	}
//	client.Domains.RenewDomain(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) RenewDomain(
	ctx context.Context,
	request *coreapigo.DomainsRenewDomainBody,
	opts ...option.RequestOption,
) (*coreapigo.RenewDomainResponse, error) {
	response, err := c.WithRawResponse.RenewDomain(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Updates WHOIS contact information for a domain. This includes the registrant, administrative, technical, and billing contacts.  All contact objects must be complete — partial updates are not supported.  You should fetch the existing contact data first (e.g., via [GetDomain](/api/v1/reference/domains/get-domain) and modify only the values you wish to change.  This call replaces all four contact sets at once.
// #### Contact Verification
// When registrant contact information is updated, validation may be triggered if the new contact information has not been previously validated. This validation is required by ICANN for all TLDs except country-code TLDs (ccTLDs). This validation involves sending an email to the provided address, prompting the recipient to click a link to verify their email address.
//
// Example:
//
//	request := &coreapigo.DomainsSetContactsBody{
//	    DomainName: "example.com",
//	    Contacts: &coreapigo.ContactsRequest{},
//	}
//	client.Domains.SetContacts(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) SetContacts(
	ctx context.Context,
	request *coreapigo.DomainsSetContactsBody,
	opts ...option.RequestOption,
) (*coreapigo.DomainResponsePayload, error) {
	response, err := c.WithRawResponse.SetContacts(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// SetNameservers will set the nameservers for the Domain. This operation updates the DNS configuration by changing which nameservers are responsible for the domain's zone.
//
// Example:
//
//	request := &coreapigo.DomainsSetNameserversBody{
//	    DomainName: "example.com",
//	    Nameservers: []string{
//	        "ns1.name.com",
//	        "ns2.name.com",
//	    },
//	}
//	client.Domains.SetNameservers(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) SetNameservers(
	ctx context.Context,
	request *coreapigo.DomainsSetNameserversBody,
	opts ...option.RequestOption,
) (*coreapigo.DomainResponsePayload, error) {
	response, err := c.WithRawResponse.SetNameservers(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Unlocks a domain to allow it to be transferred. **DEPRECATED** This endpoint is deprecated in favor of the new UpdateDomain API. This will be removed in a future release.
//
// Example:
//
//	request := &coreapigo.UnlockDomainRequest{
//	    DomainName: "domainName",
//	    Body: &coreapigo.EmptyObject{},
//	}
//	client.Domains.UnlockDomain(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) UnlockDomain(
	ctx context.Context,
	request *coreapigo.UnlockDomainRequest,
	opts ...option.RequestOption,
) (*coreapigo.Domain, error) {
	response, err := c.WithRawResponse.UnlockDomain(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Checks whether up to 50 domain names are purchasable and returns **discovery** pricing for each result.
//
// **Discovery endpoint:** Returns `SearchResult` fields — `purchaseType`, `purchasePrice`, `premium`, `purchasable`. [Search](/api/v1/reference/domains/search) returns the same fields for keyword/suggestion flows. Use this endpoint to determine what to send on [Create Domain](/api/v1/reference/domains/create-domain).
//
// When results show `premium: true` or a non-`registration` `purchaseType`, follow the [Domain pricing guide](/guides/domain-pricing) before calling Create Domain. For non-registration types, re-check Check Availability immediately before create — acquisition prices can change.
//
// **Recommendation:** Set `purchaseType` to `registration`. Most resellers
// restrict results to domains with a `purchaseType` of `registration`
// to ensure predictable pricing and immediate fulfillment. Other purchase types
// (such as aftermarket variants) can introduce higher costs and non-instant
// transactions that may be delayed or declined by third parties.
//
// Example:
//
//	request := &coreapigo.AvailabilityRequest{
//	    DomainNames: []string{
//	        "domainNames",
//	    },
//	}
//	client.Domains.CheckAvailability(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) CheckAvailability(
	ctx context.Context,
	request *coreapigo.AvailabilityRequest,
	opts ...option.RequestOption,
) (*coreapigo.SearchResponse, error) {
	response, err := c.WithRawResponse.CheckAvailability(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Searches for domain name suggestions based on a keyword or term. Important: Do not
// encode the `:` in the path. Use `/core/v1/domains:search`, not `/core/v1/domains%3Asearch`.
//
// **Discovery endpoint:** Returns `SearchResult` fields — `purchaseType`, `purchasePrice`, `premium`, `purchasable`.
//
// **Recommendation:** Set `purchaseType` to `registration`. Most resellers restrict
// results to domains with a `purchaseType` of `registration` to ensure predictable
// pricing and immediate fulfillment. Other purchase types (such as aftermarket) can
// introduce higher costs and non-instant transactions that may be delayed or declined
// by third parties.
// With `purchaseType: registration`, domains that do not match the filter are **omitted** from results (unlike Check Availability, which returns them with `purchasable: false`).
//
// When results show `premium: true` or a non-`registration` `purchaseType`, follow the [Domain pricing guide](/guides/domain-pricing) before calling Create Domain. For all types, re-check with Check Availability immediately before create — prices and availability can change.
//
// Example:
//
//	request := &coreapigo.SearchRequest{
//	    Keyword: "mydomain",
//	}
//	client.Domains.Search(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Search(
	ctx context.Context,
	request *coreapigo.SearchRequest,
	opts ...option.RequestOption,
) (*coreapigo.SearchResponse, error) {
	response, err := c.WithRawResponse.Search(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Zone Check offers a rapid, preliminary check for domain availability by leveraging cached zone file data.  Ideal for large-batch queries, it provides a high confidence indication of a domain's availability significantly faster than live registry checks.  For definitive, real-time availability and pricing, you can follow up with the standard [Check Availability](/api/v1/reference/domains/check-availability) call.
// The API normalizes and validates each submitted domain string. Domains that fail validation, use an unsupported TLD for this service, or  are otherwise not eligible for zone check are **removed** from the request before the zone file lookup runs. The response includes **only**  a numeric count of removed domains (`removed`); individual removed strings are not returned. A future API version may extend the contract to  include details about removed domains.
//
// For the best results and to avoid `400 Bad Request` errors after cleaning, ensure each domain string meets the criteria described for  `domainNames` in the request body schema.
//
// If no valid domains remain after this process, the API returns a `400 Bad Request` response.
// **Note:** The cached zone files used for this check are refreshed twice daily based on the latest available data from the registries.
//
// Example:
//
//	request := &coreapigo.ZoneCheckRequest{
//	    DomainNames: []string{
//	        "example.com",
//	        "example.net",
//	        "example.org",
//	    },
//	}
//	client.Domains.ZoneCheck(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) ZoneCheck(
	ctx context.Context,
	request *coreapigo.ZoneCheckRequest,
	opts ...option.RequestOption,
) (*coreapigo.ZoneCheckResponse, error) {
	response, err := c.WithRawResponse.ZoneCheck(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
