// Code generated by Fern. DO NOT EDIT.

package vanitynameservers

import (
	context "context"

	coreapigo "github.com/namedotcom/core-api-go"
	core "github.com/namedotcom/core-api-go/core"
	internal "github.com/namedotcom/core-api-go/internal"
	option "github.com/namedotcom/core-api-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Lists all vanity nameserver hostnames configured for a domain.
//
// Example:
//
//	request := &coreapigo.ListVanityNameserversRequest{
//	    DomainName: "example.com",
//	    PerPage: coreapigo.Int(
//	        50,
//	    ),
//	    Page: coreapigo.Int(
//	        2,
//	    ),
//	}
//	client.VanityNameservers.ListVanityNameservers(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) ListVanityNameservers(
	ctx context.Context,
	request *coreapigo.ListVanityNameserversRequest,
	opts ...option.RequestOption,
) (*coreapigo.ListVanityNameserversResponse, error) {
	response, err := c.WithRawResponse.ListVanityNameservers(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Register a new vanity nameserver for the specified domain.
//
// Example:
//
//	request := &coreapigo.CreateVanityNameserverBody{
//	    DomainName: "example.com",
//	    Hostname: "ns1",
//	    Ips: []string{
//	        "192.168.1.10",
//	        "2001:0db8:85a3:0000:0000:8a2e:0370:7334",
//	    },
//	}
//	client.VanityNameservers.CreateVanityNameserver(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) CreateVanityNameserver(
	ctx context.Context,
	request *coreapigo.CreateVanityNameserverBody,
	opts ...option.RequestOption,
) (*coreapigo.VanityNameserverResponse, error) {
	response, err := c.WithRawResponse.CreateVanityNameserver(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieves details for a of a specific vanity nameserver (including its IP addresses).
//
// Example:
//
//	request := &coreapigo.GetVanityNameserverRequest{
//	    DomainName: "example.com",
//	    Hostname: "ns1.example.com",
//	}
//	client.VanityNameservers.GetVanityNameserver(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) GetVanityNameserver(
	ctx context.Context,
	request *coreapigo.GetVanityNameserverRequest,
	opts ...option.RequestOption,
) (*coreapigo.VanityNameserverResponse, error) {
	response, err := c.WithRawResponse.GetVanityNameserver(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Updates the glue record IP addresses for a vanity nameserver.
//
// Example:
//
//	request := &coreapigo.UpdateVanityNameserverBody{
//	    DomainName: "example.com",
//	    Hostname: "ns1.example.com",
//	}
//	client.VanityNameservers.UpdateVanityNameserver(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) UpdateVanityNameserver(
	ctx context.Context,
	request *coreapigo.UpdateVanityNameserverBody,
	opts ...option.RequestOption,
) (*coreapigo.VanityNameserverResponse, error) {
	response, err := c.WithRawResponse.UpdateVanityNameserver(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Deletes a vanity nameserver from the domain’s registry settings. This operation might fail if the registry detects the nameserver is still in use.
//
// Example:
//
//	request := &coreapigo.DeleteVanityNameserverRequest{
//	    DomainName: "example.com",
//	    Hostname: "ns1.example.com",
//	}
//	client.VanityNameservers.DeleteVanityNameserver(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) DeleteVanityNameserver(
	ctx context.Context,
	request *coreapigo.DeleteVanityNameserverRequest,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.DeleteVanityNameserver(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}
