// Code generated by Fern. DO NOT EDIT.

package dnssecs

import (
	context "context"

	coreapigo "github.com/namedotcom/core-api-go"
	core "github.com/namedotcom/core-api-go/core"
	internal "github.com/namedotcom/core-api-go/internal"
	option "github.com/namedotcom/core-api-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Lists all DNSSEC (DS) records configured for a domain.
func (c *Client) ListDnsseCs(
	ctx context.Context,
	request *coreapigo.ListDnsseCsRequest,
	opts ...option.RequestOption,
) (*coreapigo.ListDnsseCsResponse, error) {
	response, err := c.WithRawResponse.ListDnsseCs(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Adds (registers) a new DNSSEC DS record for a domain.
func (c *Client) CreateDnssec(
	ctx context.Context,
	request *coreapigo.CreateDnssecBody,
	opts ...option.RequestOption,
) (*coreapigo.Dnssec, error) {
	response, err := c.WithRawResponse.CreateDnssec(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieves details of a specific DNSSEC record for a domain.
func (c *Client) GetDnssec(
	ctx context.Context,
	request *coreapigo.GetDnssecRequest,
	opts ...option.RequestOption,
) (*coreapigo.Dnssec, error) {
	response, err := c.WithRawResponse.GetDnssec(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Deletes a DNSSEC record from a domain.
func (c *Client) DeleteDnssec(
	ctx context.Context,
	request *coreapigo.DeleteDnssecRequest,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.DeleteDnssec(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}
