// Code generated by Fern. DO NOT EDIT.

// Use DNSSEC endpoints to configure DNS Security Extensions for your domains. These endpoints allow you to add, retrieve, or remove DNSSEC records.
package dnssecs
